.changeset/hungry-schools-shake.md, .github/workflows/release.yaml, CHANGELOG.md
Removes changelog and fixes yaml
=> Prepare for release

.changeset/hungry-schools-shake.md, .github/workflows/release.yaml, CHANGELOG.md
=> Change token secret name

.changeset/config.json
- Make package public so we can publish through the repo
=> make package public

src/components/core/drawer.tsx
Deleted image as this repo will be open source (Luthfi)
=> Ctw 313 embeddable boost z index value of zus drawer in healthie

.changeset/tender-badgers-talk.md, README.md, src/App.tsx, src/components/core/ctw-provider.tsx, src/fhir/client.ts
- Allow headers to be passed into component
=> Ctw 320/pass session info

src/index.ts
Remove export for conditions table that file no longer exists
=> remove conditions table export

.eslintrc.cjs, .github/workflows/validate-pr.yml, .github/workflows/validate.yml, .prettierignore, package-lock.json, package.json, scripts/prefixer/prefixer.ts, src/components/content/condition-form-drawer.tsx, src/components/content/conditions-drawer.tsx, src/components/content/conditions.tsx, src/components/core/button-tabs.test.tsx, src/components/core/ctw-provider.tsx, src/components/core/drawer.tsx, src/components/core/table/table-full-length-row.tsx, src/fhir/formatters.test.ts, src/styles/tailwind.theme.ts, tailwind.config.cjs, tsconfig.json, vitest.config.ts, vitest.env.ts
=> Cleanup lint issues & setup CI

.changeset/cuddly-wasps-work.md, src/components/content/conditions.tsx, src/fhir/conditions.ts, src/fhir/search-helpers.ts
Setup more active statuses for condition query. Also remove filter from lens as we will always fetch whatever lens has.
=> CTW-270/include more active statuses

README.md
Add documentation on adding changeset
=> add doc on adding changeset

.github/workflows/release.yaml
It did indeed trigger the workflow but it wasn't against the PR branch and so it didn't resolve the CI checks.
=> Remove workflow trigger

.changeset/nervous-cameras-beam.md, package-lock.json, package.json, src/App.tsx, src/components/content/conditions.tsx, src/components/core/dropdown-menu.tsx, src/components/core/toggle.tsx, src/fhir/conditions.ts, src/index.ts, src/styles/tailwind.css, vite.config.ts
Numerous tweaks to get embedding conditions working in CTW app. I worked on this while copying the `dist` folder over to my CTW App's `node_modules` directory so that I can test things out. Likely more testing and tweaks needed after this gets pushed to NPM.
* Switch to use `.cjs` extension for cjs module files. This way they do not get picked up, and we instead correctly pick up the `es.js` files.
* Attempt to setup better reference for style.css.
* Fix how typings are specified.
* Switch app to use dev environment.
* Export patient provider component.
* Tweak a few styles.
* Sort conditions by name.
* Work around dropdown menu position issue.
=> CTW-173/embed conditions

.changeset/forty-dryers-deny.md, package-lock.json, package.json, src/components/core/dropdown-menu.tsx, src/components/core/table/table-rows.tsx, src/styles/tailwind.css
This fixes an issue where the previous headlessui-float library had glitchy placement and arrow setup.
=> Switch to dropdown menu from radix library

.changeset/swift-feet-collect.md, README.md, package-lock.json, package.json
Had an issue importing style.css via `import ctwStyles from "@zus-health/ctw-component-library/style.css";`, even though the package.json maps it to the correct `dist` directory. Instead we'll have users include it directly off of the `dist` directory.
Update README file to provide install & setup instructions.
=> Quick style fix & update README

.changeset/weak-points-tickle.md
Update changeset for the change to fetch the icd10 and snomed codes via filter
=> Update changeset for fetch

.changeset/tough-rice-remain.md, .env.example, package-lock.json, src/components/core/table/table-data-cell.tsx, src/components/core/table/table-head.tsx, src/components/core/table/table-rows.tsx, src/components/core/table/table.tsx, src/styles/tailwind.css
Removed sticky column and supporting shadows.
=> Simplify tables

.changeset/brown-pumas-melt.md, README.md, package-lock.json, package.json, src/App.css, src/components/content/conditions.scss
Also fixed bg of main conditions container.
=> Re add style.css as consumers still need to include it

.changeset/neat-pumpkins-roll.md, src/components/content/forms/condition-helpers.ts
Hide condition id from edit/add
=> Hide id field

.changeset/silly-houses-sort.md, CHANGELOG.md, src/components/content/conditions.tsx, src/components/content/forms/condition-helpers.ts, src/fhir/conditions.ts
Changes labels from: 
- Confirmed  -change to- Patient Record
- Not Reviewed  -change to- Other Provider Records
As well renaming variable names to keep consistency and minor changelog changes
=> Ctw 351/update condition table labels

.changeset/spotty-pens-hammer.md, src/utils/request.ts
=> dont refetch on window focus

.changeset/wicked-waves-call.md, src/components/content/conditions-history-drawer.tsx, src/components/content/conditions-no-patient.tsx, src/components/content/conditions.tsx, src/fhir/conditions.ts
**NOTE TO REVIEWER: Best to review commit at a time as I refactored some code without making many changes to that code.**
=> Misc condition fixes

.changeset/chilled-yaks-hug.md, src/components/content/forms/conditions.ts
Fix bug where recorder field wasn't updated when adding, and was only updated when editing.
=> fix bug where practitioner id was not being updated when adding

.changeset/ten-dingos-jump.md, package-lock.json, src/components/content/conditions-table-base.tsx, src/components/content/conditions.tsx, src/components/core/table/table-rows.tsx, src/components/core/table/table.tsx
Ticket: [CTW-385](https://zeushealth.atlassian.net/browse/CTW-385)
=> [CTW-385] Add "Add Conditions" button and change text

.changeset/cool-owls-warn.md, src/components/content/conditions-history.tsx, src/fhir/formatters.ts
Quick PR to remove the unnecessary function
=> Removal of unnecessary function

.changeset/nervous-terms-rush.md, .changeset/ninety-rockets-kneel.md, src/components/core/patient-provider.tsx, src/fhir/conditions.ts, src/fhir/patient-helper.ts, src/fhir/patient.ts, src/fhir/search-helpers.ts, src/fhir/system-urls.ts, src/fhir/types.ts, src/hooks/use-breakpoints.ts
* Minor code cleanup to `useBreakpoints` (remove incorrect "class").
* Fix condition history bug (see commit message)
* Add optional `tags` prop to `PatientProvider` .. this required a little refactor in how we handle searchParams and some plumbing of `tags` down to the search queries.
=> Ctw 431/add tag patient filtering

.changeset/chatty-boxes-clean.md, src/utils/form-helper.ts
Follow up to remove unnecessary code.
=> Remove unncessary code

.changeset/thin-tomatoes-pump.md, src/components/core/ctw-provider.tsx, src/index.ts
[CTW-401](https://zeushealth.atlassian.net/browse/CTW-401)
- Added library version to window global variable
- Exported library version so customer can use it in their own debug view
=> [CTW-401] Add way to check library version for component library

src/components/content/patient-medications.tsx, src/fhir/medications.ts, src/hooks/use-medications.ts
Pair coding w/ Mike/APS/Tai, fixing medication information source filter and renaming a bunch of vars for clarity.
=> Fixing medication query filter, should exclude patient submitted meds

.changeset/tricky-gifts-cry.md, src/components/content/patient-medications.scss, src/components/core/table/table.scss
https://www.loom.com/share/5afad7ebfef14055a620a558cae5da05
=> [CTW-428] Table does not overflow anymore

.changeset/cold-cups-run.md, src/components/content/forms/drawer-form-with-fields.tsx, src/components/content/forms/form-field.tsx, src/components/content/forms/medications.ts, src/components/content/medications/add-new-med-drawer.tsx, src/fhir/medication.ts
Ticket: [CTW-304](https://zeushealth.atlassian.net/browse/CTW-304)
- added label-related parameters
- sorted med statuses
- changed `rxNorm` -> `dosage` text field
- some lint reorganizing
https://user-images.githubusercontent.com/86961468/199103086-e1c4e7b7-7549-4c61-a089-f58fb5a1bf2e.mov
=> [CTW-304] Add medication fixes

.changeset/fair-laws-whisper.md, src/components/content/conditions-history.tsx, src/components/core/coding-list.tsx, src/components/core/notes-list.tsx
[CTW-366](https://zeushealth.atlassian.net/jira/software/projects/CTW/boards/49?selectedIssue=CTW-366)
This PR adds recorder field and notes field to the condition history page.
=> Ctw 366/add fields history

.changeset/lemon-ways-thank.md, src/components/content/medication-history.tsx
=> CTW-399 date time regression

.changeset/breezy-bears-beam.md, package-lock.json, package.json, src/components/content/medication-history.tsx
Updated the node versions allowed and then ran `npm install` while on 18.11.0 to verify no issues on the engine check for us. Also verified it yelled if we used an engine outside the range.
=> Node engines use gt 16 lt 19

.changeset/rude-doors-think.md, src/components/content/conditions.tsx
CTW-512 
Hide delete in other patient records.
=> Ctw 512/hide delete in other patient records

.changeset/seven-mice-watch.md, src/components/content/forms/conditions.ts, src/components/content/forms/medications.ts
CTW-507
Fix delayed UX when adding condition.
=> await queries to avoid drawer closing before time

src/components/content/medication-drawer.tsx
Added missing "ctw-" prefix to "ctw-btn-primary" class in MedicationDrawer
=> added missing "ctw-" prefix to "ctw-btn-primary" class in MedicationDrawer

.changeset/green-beds-speak.md, src/components/content/conditions-helper.ts, src/components/content/conditions.tsx, src/components/content/forms/conditions.ts, src/components/core/modal-confirm-delete.tsx, src/fhir/conditions.ts, src/models/condition.ts
CTW-538
Delete functionality for validation status now edits to entered-in-error instead of deleting.
=> Ctw 538/delete condition enters in error instead of delete

.changeset/shiny-olives-sort.md, src/components/content/conditions/helpers.test.ts, src/components/content/conditions/helpers.ts
CTW-518
We now exclude other provider conditions that have the same status as an existing condition.
=> CTW-518/filter summaries with same status

.changeset/fluffy-days-exercise.md, .storybook/preview.js, .storybook/preview.scss, src/components/content/medication-history/index.tsx, src/components/content/medication-history/medication-history.stories.tsx, src/components/content/medication-history/mocks/aggregated-from-med-statement.ts, src/components/content/medication-history/mocks/medication-dispense.ts, src/components/content/medication-history/mocks/medication-request.ts, src/components/content/medication-history/mocks/medication-statements.ts, src/components/content/medication-history/mocks/patient.ts, src/components/content/medications/mocks/other-provider-medications.ts, src/components/content/medications/other-provider-meds-table.stories.tsx, src/components/content/medications/other-provider-meds-table.tsx, src/components/content/medications/provider-meds-table.stories.tsx, src/components/content/medications/provider-meds-table.tsx, src/components/core/action-list/action-list.stories.tsx
The meds tables were sorting by alphanumerical, but they were case sensitive, (`apple`, `book`, `Ant`, `Cat`). Now the sorted values are normalized first so the order would instead be (`Ant`, `apple`, `book`, `Cat`).
Additionally added these 2 tables as stories into storybook with mocked requests.
=> fixed the sort and added stories for the two tables

.changeset/short-zebras-press.md, src/components/content/conditions.tsx, src/components/content/conditions/conditions.stories.tsx, src/components/content/conditions/mocks/forms-data-conditions-search.ts, src/components/content/conditions/mocks/history-crohns-disease.ts, src/components/content/conditions/mocks/history-dermatitis.ts, src/components/content/conditions/mocks/history-generalized-anxiety.ts, src/components/content/conditions/mocks/history-iron-deficiency.ts, src/components/content/conditions/mocks/history-oral-contraception.ts, src/components/content/conditions/mocks/other-conditions.ts, src/components/content/conditions/mocks/patient-conditions.ts, src/components/content/conditions/mocks/patient.ts, src/components/content/forms/condition-schema.tsx, src/components/content/forms/conditions.ts, src/fhir/conditions.ts
CTW-523
Add condition stories and fix a few bugs:
1. Don't show multiple `required` condition errors when adding a condition.
2. Hide empty table's Add Condition button when readOnly
3. Don't modify the actual other provider condition when adding and setting default
=> CTW-523/storybook conditions

.changeset/bright-candles-think.md, src/fhir/models/medication.ts
Following a medication component data deep dive we have resolved to fall back to `whenPrepared` for med dispense and `dosageInstruction.timing.repeat.boundsPeriod` for med request.
=> CTW-559/CTW-560 Updating logic for med dispense/request dates

.changeset/weak-buses-fly.md, src/components/content/forms/patients.ts
Fix bug where managing org was added when it was not present.
=> Fix managing organization patient bug

.changeset/flat-dogs-listen.md, src/components/content/forms/form-field-label.tsx, src/components/content/forms/request-history-schema.tsx, src/components/core/form/drawer-form-with-fields.tsx, src/components/core/main.scss
Add ability to include multiple elements in one row in forms.
Still need to:
=> Ctw 536/multiple elem in single row

.changeset/poor-ligers-smash.md, src/components/content/conditions.tsx, src/components/content/forms/patients.ts, src/fhir/models/patient.ts
Use whatever the patient already has for `use` else set it to official.
=> Use official in patient edit

.changeset/young-icons-warn.md, package-lock.json, package.json, src/components/content/conditions/conditions.stories.tsx, src/components/content/conditions/helpers.ts, src/components/content/conditions/patient-conditions-actions.tsx, src/components/content/conditions/patient-conditions-columns.tsx, src/components/content/conditions/patient-conditions-filters.tsx, src/components/content/conditions/patient-conditions-header.tsx, src/components/content/conditions/patient-conditions.scss, src/components/content/conditions/patient-conditions.stories.tsx, src/components/content/conditions/patient-conditions.tsx, src/components/content/conditions/story-helpers/mocks/other-conditions.ts, src/components/content/conditions/story-helpers/mocks/patient-conditions.ts, src/components/core/badge.tsx, src/components/core/buttons.scss, src/components/core/main.scss, src/components/core/table/table.tsx, src/components/core/toggle.tsx, src/fhir/conditions.ts, src/fhir/mappings/ccs-chapter-names.ts, src/fhir/models/condition.ts, tailwind.config.cjs
First pass at setting up new `PatientConditions` component (conditions 2.0). Special care is taken to try and reduce how much code is actually in the main component and instead rely on more helpers. Also worth noting that filtering does not happen within a `useEffect` as it should be fast and it is ok if it happens every time the component re-renders.
TODO:
* Pagination
* "..." menu
=> CTW-572/patient conditions component

.changeset/slimy-ducks-guess.md, package-lock.json, src/api/autocomplete-conditions.ts, src/api/patient-history.ts, src/components/core/ctw-provider.tsx, src/fhir/client.ts, src/services/patient-history/patient-history.ts, src/utils/request.ts
Reverts zeus-health/ctw-component-library#315
=> Revert "CTW-555 request header"

.changeset/afraid-ways-hang.md, src/components/core/form/drawer-form.tsx
Actions will now catch unhandled errors.
=> ctw-601/fix-condition-latency

.changeset/many-snakes-smell.md, src/components/core/collapsible-data-list-stack.tsx
Add label "History" to history records.
=> Ctw 599/add history label

.changeset/proud-llamas-fold.md, src/components/content/forms/conditions.ts, src/fhir/system-urls.ts
CTW-571
Automatically categorizes new conditions as problem list item.
=> CTW-571 automatically save conditions as problems

.changeset/friendly-berries-tease.md, .changeset/quiet-cats-repeat.md, .changeset/slimy-ducks-guess.md, package-lock.json, src/api/autocomplete-conditions.ts, src/api/patient-history.ts, src/components/core/ctw-provider.tsx, src/fhir/client.ts, src/services/patient-history/patient-history.ts, src/utils/request.ts
Reverts zeus-health/ctw-component-library#319
[Original PR](https://github.com/zeus-health/ctw-component-library/pull/315)
=> Revert "Revert "CTW-555 request header""

.changeset/eleven-bulldogs-kneel.md, src/components/core/collapsible-data-list-stack.tsx, src/components/core/form/drawer-form.tsx
Add error message at bottom of drawer in addition to top of drawer.
=> Ctw 600/add error msg to bottom

.changeset/silly-bags-relate.md, src/api/autocomplete-medications.ts, src/api/urls.ts, src/components/content/forms/conditions-autocomplete.tsx, src/components/content/forms/medications-autocomplete.tsx, src/components/content/forms/medications.tsx, src/components/core/collapsible-data-list-stack.tsx
This pr:
- Adds new medications dropdown
- Renames dosage to instructions 
- Remove note field as it is not used
=> Ctw 151/auto complete medications

.changeset/twenty-drinks-cross.md, src/api/autocomplete-conditions.ts, src/api/autocomplete-medications.ts, src/api/patient-history.ts, src/components/content/forms/conditions-autocomplete.tsx, src/components/content/forms/medications-autocomplete.tsx, src/components/core/collapsible-data-list-stack.tsx, src/components/core/ctw-context.tsx, src/components/core/ctw-provider.tsx, src/services/patient-history/patient-history.ts
Fix issue where zus-account header was still being passed even when logged in normal user.
=> Ctw 623/fix builder impoersonation issue

.changeset/wild-lions-tie.md, src/components/content/forms/medications.tsx
Fix bug where medications couldnt be added without dosage.
=> Fix bug where medications couldnt be added without dosage.

src/components/content/forms/medications.tsx, src/components/core/form/drawer-form.tsx, src/fhir/action-helper.ts, src/fhir/provenance.ts
When creating a med now a Bundle transaction will be used so that a Provenance may also be used.
=> CTW-499/create medication transaction with provenance

.changeset/late-peaches-press.md, package-lock.json, package.json, src/components/content/patients/patients-table.scss, src/components/content/patients/patients-table.stories.tsx, src/components/content/patients/patients-table.tsx, src/components/content/patients/story-helpers/mocks/patient-bundle.ts, src/components/content/patients/story-helpers/mocks/requests.ts, src/components/core/ctw-provider.tsx, src/components/core/form/drawer-form.tsx, src/components/core/pagination/pagination-list.tsx, src/components/core/pagination/pagination.scss, src/components/core/pagination/pagination.tsx, src/components/core/table/table.tsx, src/fhir/models/patient.ts, src/fhir/patient-helper.ts, src/index.ts, src/utils/query-keys.ts
- Created `<PatientTable />` component based on the one in ctw.
- Created a new `<Pagination />` component that lazy fetches and caches pages.
- The pagination component previously used is now named `<PaginationList />` because the newer pagination component more aptly fits the description of "paging". The older pagination was only used internally by components, should be no issue with name change.
- Added storybook story for patients table. The story uses the faker js library to generate fhir resources for the mocked API.
=> CTW-597/PatientTable

.changeset/little-monkeys-invent.md, package-lock.json, package.json, src/components/content/CCDA/base64toBinaryField.tsx, src/components/content/CCDA/reactViewer.tsx, src/components/content/conditions-history.tsx
This fix is to address CTW document error
=> Fix for ctw issue

.changeset/stupid-apples-pump.md, src/components/content/condition-header.tsx, src/components/content/conditions/conditions.stories.tsx, src/components/content/conditions/story-helpers/condition-form-drawer.ts, src/components/content/forms/actions/conditions.ts, src/components/content/forms/form-field.tsx, src/components/content/forms/schemas/condition-schema.tsx, src/components/content/forms/types.ts
Update edit/add conditions panel to automatically fill in verification and clinical status based on the status value in the dropdown.
=> Ctw 590/update edit add conditions panel

.changeset/cool-singers-learn.md, src/components/content/CCDA/ccda_viewer/components/Authenticator/data.ts, src/components/content/CCDA/ccda_viewer/components/Document/data.ts, src/components/content/CCDA/ccda_viewer/components/Header/data/getAuthor.ts, src/components/content/CCDA/ccda_viewer/components/Header/data/getDocumentationOf.ts, src/components/content/CCDA/ccda_viewer/components/Header/data/getEncounter.ts, src/components/content/CCDA/ccda_viewer/components/Header/data/getPatient.ts, src/components/content/CCDA/ccda_viewer/components/Header/data/getTitle.ts, src/components/content/CCDA/ccda_viewer/components/LegalAuthenticator/data.ts, src/components/content/CCDA/ccda_viewer/helpers/formatDate.ts, src/components/content/CCDA/ccda_viewer/helpers/getPeriod.ts, src/components/content/CCDA/ccda_viewer/helpers/index.ts, src/components/content/CCDA/ccda_viewer/helpers/parseToISOString.ts, src/fhir/formatters.ts
This reverts date changes to fix the date being off or not showing up.
=> Revert date changes

.changeset/stale-schools-know.md, src/components/content/conditions/patient-conditions-menu-actions.tsx
Rename Archive button to Dismiss. Rename Un-Archive button to Restore.
=> Ctw 592 qc feedback

.changeset/famous-clocks-develop.md, src/components/content/conditions/conditions.stories.tsx, src/fhir/models/condition.ts
Fix logic for Pending case in verification status.
=> Fix pending case

.changeset/healthy-carrots-judge.md, src/components/content/timeline/patient-timeline-columns.tsx, src/components/content/timeline/patient-timeline.scss, src/components/content/timeline/patient-timeline.stories.tsx, src/components/content/timeline/patient-timeline.tsx, src/components/content/timeline/story-helpers/mocks/encounters.ts, src/components/content/timeline/story-helpers/mocks/patient.ts, src/components/content/timeline/story-helpers/mocks/requests.ts, src/fhir/encounters.ts, src/fhir/models/encounter.ts, src/fhir/system-urls.ts, src/index.ts, src/utils/query-keys.ts
CTW-649
This is a first pass at a new timeline component. Many more features and refinements to come!
[CTW-649]: https://zeushealth.atlassian.net/browse/CTW-649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add new PatientTimeline component for encounters

src/fhir/encounters.ts
Map changed from object to Map syntax
=> Fix usage of basics map

.changeset/tender-bulldogs-smoke.md, package-lock.json, src/components/content/condition-history/conditions-history-drawer.tsx, src/components/content/timeline/encounter-details-drawer.tsx, src/components/content/timeline/patient-timeline-columns.tsx, src/components/content/timeline/patient-timeline.tsx, src/components/content/timeline/story-helpers/mocks/encounters.ts, src/components/core/coding-list.tsx, src/components/core/drawer.tsx, src/components/core/form/drawer-form.tsx, src/fhir/models/encounter.ts
=> CTW-651/encounter details

.changeset/neat-apes-cheer.md, src/components/content/timeline/encounter-details-drawer.tsx, src/components/content/timeline/story-helpers/mocks/encounters.ts, src/fhir/models/encounter.ts
=> Add encounter class to encounter details drawer

.changeset/shy-bulldogs-film.md, src/components/content/medications/other-provider-meds-table.tsx, src/components/core/action-list/action-list.stories.tsx, src/components/core/action-list/action-list.tsx, src/fhir/medications.ts, src/index.ts
- `<ActionList/>` supports a secondary action button having the same styling of the primary action.
- Added `useDismissMedication` hook which just creates a dismissMedication function.
=> ActionList supports second action

.changeset/polite-crews-argue.md, src/components/core/pagination/pagination-list.tsx, src/components/core/pagination/pagination.scss, src/components/core/table/table.scss
This PR updates pagination for all the embedded component tables. 
Original view for the table:
=> CTW-594/update-pagination-2.0

.changeset/selfish-snakes-prove.md, src/components/core/action-list/action-list.tsx
Change the order of the secondary and primary buttons on the `<ActionList/>` component.
=> Reorder action list buttons

.changeset/quick-hats-melt.md, src/components/content/conditions/patient-conditions.scss
This PR fixes spacing for underline
=> Spacing fix

.changeset/nasty-paws-applaud.md, src/index.ts
=> export component

.changeset/new-singers-sell.md, src/components/content/allergies/allergies-filter.tsx, src/components/content/allergies/patient-allergies-column.tsx, src/components/content/immunizations/patient-immunizations-filters.tsx, src/fhir/allergies.ts, src/fhir/immunizations.ts, src/utils/nodash/fp.ts
This PR dedupes allergies and adds the manifestation column. Additionally, it dedupes immunizations as well.
=> Allergies updates and dedupe

.changeset/slow-stingrays-accept.md, src/components/content/conditions/patient-conditions.stories.tsx, src/components/content/conditions/patient-conditions.tsx
=> Add empty state for conditions 2.0 and remove x padding.

package-lock.json, src/utils/telemetry.ts
Need to guard against use of `window`
=> Fix telemetry issue in SSR

.changeset/spotty-fishes-battle.md, src/components/content/conditions.tsx, src/components/content/conditions/conditions.stories.tsx, src/components/content/patient-history/patient-history-message.tsx
=> Add ability to hide request records in conditions

.changeset/tidy-coins-relate.md, package-lock.json, src/components/content/conditions.tsx, src/components/content/patient-history/patient-history-message-status.tsx
CTW-473
This PR adds status message and Last Retrieved date (if there is one) to the other providers table.
=> CTW-473/status refresh

.changeset/kind-mirrors-give.md, src/components/content/conditions.tsx
This is a quick PR to fix date while I work on the refactor of the drawer (mainly focusing on having this fixed for demo).
=> Fix date temp

.changeset/cyan-colts-act.md, src/components/content/allergies/allergies-filter.tsx, src/components/content/immunizations/patient-immunizations-filters.tsx, src/components/content/patient-history-request-drawer.tsx, src/components/content/patient-history/use-patient-history.tsx, src/utils/query-keys.ts
This PR updates the refresh state on save for patient history and fixes dedupe in allergies and immunizations.
=> Fixed bug with dedupe and fixed refresh

.changeset/sweet-shirts-yawn.md, src/components/content/conditions/patient-conditions-actions.tsx, src/components/content/patient-history/patient-history-table-header.tsx
This PR adds the date for the case regardless of state (specifically error) for both conditions 1.0 and 2.0.
=> Fix last retrieved

.changeset/healthy-bags-jump.md, src/components/content/timeline/patient-timeline-columns.tsx, src/components/content/timeline/patient-timeline.stories.tsx, src/components/content/timeline/patient-timeline.tsx
Make fhir button optional on patient timeline.
=> remove fhir button

.changeset/lemon-teachers-matter.md, src/components/content/patient-history/patient-history-message-status.tsx
=> Bug fix for done state

src/App.tsx, src/components/content/conditions/conditions.stories.tsx, src/components/content/conditions/patient-conditions-actions.tsx, src/components/content/conditions/patient-conditions-tabs.tsx, src/components/content/conditions/patient-conditions.scss, src/components/content/conditions/patient-conditions.tsx, src/components/core/tab-group/tab-group.scss, src/components/core/tab-group/tab-group.tsx
Migrated `PatientConditionsTabs` to the `TabGroup` component.
=> CTW-760/Conditions alignment with v2.0 TabGroup component

.changeset/sharp-garlics-sleep.md, src/components/content/conditions/patient-conditions.tsx
Added prop to hide builder records and tabs in patient conditions component.
=> CTW-700 Prop to hide builder records

.changeset/mighty-maps-flash.md, .changeset/rich-rings-sin.md, src/App.tsx, src/components/content/conditions.tsx, src/components/content/conditions/story-helpers/conditions.ts, src/components/content/medications/patient-medications.tsx, src/components/content/medications/story-helpers/patient-medications.ts, src/components/core/error-boundary.tsx
- Copied classes from "Add condition" button to "Add medication" button
- All buttons use `"This casing"` and not `"Title Casing"`
- Title casing determined by CSS so customers can opt out if desired
=> CTW-511/Minor button styles

.changeset/perfect-moose-do.md, src/components/content/conditions/patient-conditions-sort.tsx
Fix condition default sorting bug
=> Fix conditions sort

.changeset/dirty-parents-fetch.md, src/App.tsx, src/components/content/conditions/patient-conditions-actions.tsx, src/components/content/conditions/patient-conditions.tsx
Fixing the logic to show up by default unless the prop is provided
=> Fix request records logic 

.changeset/cold-turkeys-pull.md, src/index.ts
Export patientSearch component.
=> export search

.changeset/odd-pots-lay.md, package-lock.json, package.json
=> lock headless ui version

.changeset/tough-countries-melt.md, src/utils/telemetry.ts
Disable sending metrics to CTW from localhost:3000
=> disable metrics from localhost 3000

.changeset/modern-crabs-cry.md, src/components/content/care-team/patient-careteam-columns.tsx, src/components/content/document/patient-document-columns.tsx, src/components/content/timeline/patient-timeline-columns.tsx, src/components/content/timeline/patient-timeline.tsx
Set feature flags for view FHIR functionality to false.
=> Default feature flags off 

.changeset/purple-coats-remember.md, src/App.tsx, src/components/content/patients/patients-table.tsx, src/components/core/table/table.tsx
Fix bug where patient list wasn't always showing all patients for some consumers.
=> Ctw 850/patient list bugfix

.changeset/early-tips-travel.md, src/components/content/medications/helpers/patient-medications-base.tsx
Add ctw-scrollable-pass-through-height class
=> Meds/Add ctw-scrollable-pass-through-height class

.changeset/lovely-oranges-hammer.md
Bumps our component library to 1.0.
=> 1.0 release

.changeset/young-shoes-explode.md, src/components/core/table/table-helpers.tsx, src/components/core/table/table-rows.tsx, src/components/core/table/table.stories.tsx, src/components/core/table/table.tsx, src/fhir/models/careteam-practitioner.ts, src/fhir/models/fhir-model.ts, src/utils/telemetry.ts
CareTeamPractitionerModel now uses "key" for table row identification.
=> Quick fix for telemetry env and CareTeam table rows

.changeset/wise-socks-marry.md, src/components/content/care-team/patient-careteam.tsx, src/components/content/immunizations/patient-immunizations.tsx
Fix bug with careteams and immunizations
=> Fix source document for careteams and immunizations

.changeset/nice-weeks-hammer.md, src/App.tsx, src/components/content/patient-history/patient-history-last-retrieved.tsx, src/components/content/patient-history/patient-history-message-status.tsx, src/components/content/patient-history/use-patient-history.tsx, src/components/core/tab-group/tab-group.tsx, src/services/patient-history/patient-history-types.ts
- Show patient history status in the mega zap component
- If an error occurs, notify the user that the request was not completed
=> Add patient history request status to the ZusAggregatedProfile

.changeset/sharp-mice-grab.md, src/components/content/patient-history/patient-history-last-retrieved.tsx
Fix spacing with last retrieved date.
=> fix spacing with last retrieved date

.changeset/empty-mails-cross.md, src/components/content/patient-history/patient-history-table.tsx, src/index.ts
Export patient history table. Add handleClickRow handler to table.
=> Export patient history table

.changeset/red-readers-attend.md, src/components/content/patient-history/use-builder-patient-history-list.ts
use useQueryWithCTW instead of useQueryWithPatient in patient history table.
=> Change useQuery in patient history table

.changeset/soft-radios-compete.md, src/components/content/allergies/allergies-filter.tsx, src/components/content/resource/resource-details-drawer.tsx, src/fhir/medications.ts, src/utils/sort.ts
CTW-935
This PR fixes Allergies Deduping logic by sorting and then deduping. 
There is still an inherent question to be answered but for the time being this should potentially suffice (will get product feedback on Monday). 
Don't merge right away
=> Fix Allergies Dedupe

.changeset/hungry-tools-explain.md, src/App.tsx, src/components/content/observations/helpers/details.tsx
=> feat: add source document link to observation drawer

.changeset/old-eels-arrive.md, src/api/urls.ts, src/components/core/providers/ctw-provider.tsx, src/fhir/search-helpers.ts
CTW-855
This PR fixes the post and pre kludge by adding a conditional to make sure based on environment the data is being obtained in the old/new fashion.
=> Kludge attempt

.changeset/silent-eels-beam.md, src/App.tsx, src/api/patient-history.ts, src/components/content/conditions/helpers/patient-conditions-base.tsx, src/components/content/conditions/story-helpers/mocks/patient-history-message.ts, src/components/content/conditions/story-helpers/mocks/requests.ts, src/components/content/patient-history/helpers/filters.tsx, src/components/content/patient-history/patient-history-message-status.tsx, src/components/content/patient-history/patient-history-table.tsx, src/components/content/patient-history/story-helpers/mocks/patient-history.ts, src/components/content/patient-history/story-helpers/mocks/requests.ts, src/components/content/patient-history/use-builder-patient-history-list.ts, src/components/content/patient-history/use-patient-history.tsx, src/components/content/patients/patients-table.tsx, src/components/core/filter-bar/filter-bar-types.ts, src/components/core/pagination/pagination.scss, src/components/core/pagination/simple-pagination.tsx, src/components/core/tab-group/tab-group.tsx, src/components/core/table/table.tsx, src/fhir/models/patient-history.ts, src/hooks/use-filtered-sorted-data.ts, src/services/patient-history/patient-history-types.ts, src/styles/tailwind.theme.ts
- Convert to all patient history requests to new JSON compliant api endpoints. 
- Fix bug where not all patient history results came back due to looping over patients first instead of messages. 
- UI fixes for patient history table.
=> Ctw 974/update to new jobs endpoint

.changeset/honest-beers-fetch.md, src/components/content/patient-history/patient-history-table.tsx
Fix bug where in_progress and done_with_errors don't filter correctly in patient history table.
=> Ctw 974/fix filter bug

.changeset/clean-boxes-confess.md, src/components/content/allergies/patient-allergies.tsx, src/components/content/care-team/patient-careteam.tsx, src/components/content/conditions/patient-conditions-outside.tsx, src/components/content/conditions/patient-conditions.tsx, src/components/content/document/patient-documents.tsx, src/components/content/immunizations/patient-immunizations.tsx, src/components/content/medications/patient-medications-outside.tsx, src/components/content/medications/patient-medications.tsx, src/components/content/observations/patient-observations-outside.tsx, src/components/content/observations/patient-observations.tsx, src/components/content/timeline/patient-timeline.tsx, src/components/core/error-boundary.tsx, src/utils/telemetry.ts
Reverts zeus-health/ctw-component-library#678
=> Revert "CTW-1006 Updated metrics"

.changeset/slimy-mangos-press.md, src/components/content/patient-history/use-patient-history.tsx
Fix issue where error occurred when patient had never made any patient history requests.
=> Ctw 974/fix empty response error

.changeset/nasty-brooms-double.md, src/App.tsx, src/components/content/conditions/patient-conditions.tsx, src/components/content/observations/patient-observations-outside-badge.tsx, src/components/content/observations/patient-observations-outside.tsx, src/components/content/observations/patient-observations.tsx, src/components/content/zus-aggregated-profile/zus-aggregated-profile.tsx, src/components/core/error-boundary.tsx, src/components/core/providers/ctw-provider.tsx, src/fhir/allergies.ts, src/fhir/care-team.ts, src/fhir/conditions.ts, src/fhir/diagnostic-report.ts, src/fhir/document.ts, src/fhir/encounters.ts, src/fhir/immunizations.ts, src/fhir/medications.ts, src/fhir/timeline-event.ts, src/utils/telemetry.test.ts, src/utils/telemetry.ts
- Added metric for component failures
- Added metrics for counts of records returned by Zus
- Removed interaction tracking (we may return to this someday but right now it's a lot of noise that we aren't getting value out of)
- A bunch of renaming to help distinguish builder records vs summary records vs CPR records
=> CTW-1006 Metrics for component loading, crashing and stats on record counts

.changeset/chilled-terms-tie.md, src/App.tsx, src/components/content/timeline-2.0/helpers/filters.tsx, src/components/content/timeline-2.0/helpers/modal-hooks.tsx, src/components/content/timeline-2.0/patient-timeline.tsx, src/components/content/zus-aggregated-profile/zus-aggregated-profile-tabs.tsx, src/components/content/zus-aggregated-profile/zus-aggregated-profile.stories.tsx, src/components/content/zus-aggregated-profile/zus-aggregated-profile.tsx, src/components/core/providers/drawer-provider.tsx, src/fhir/models/timeline-event.ts, src/fhir/timeline-event.ts
CTW-969
This PR resolves the MRT in ZAP and resolves the timeline bug currently by removing meds from the timeline while we address the issue.
=> Patient-timeline in ZAP

.changeset/swift-suits-run.md, src/utils/invalidate-queries.ts
Add a way to invalidate all queries in the cache.
=> Ctw 646/expose invalidate queries

src/fhir/allergies.ts, src/fhir/care-team.ts, src/fhir/conditions.ts, src/fhir/diagnostic-report.ts, src/fhir/document.ts, src/fhir/encounters.ts, src/fhir/immunizations.ts, src/fhir/medications.ts, src/hooks/use-medications.ts, src/utils/telemetry.ts
- Separating metrics for timing, record counts and "zero moments"
- Using histogram metric type for record counts
=> CTW-1006 Adjusting metrics

.changeset/curvy-books-teach.md, src/utils/telemetry.test.ts, src/utils/telemetry.ts
Adds version tag to metrics so we can detect what versions are being used.
=> Adding version to metrics

.changeset/gorgeous-tomatoes-raise.md, src/fhir/patient-helper.ts
Sorting patient list by last name. Currently not sorted by anything so they appear in random order. Please just merge upon approval.
=> Sorting patient list by last name

.changeset/slow-rules-repair.md, src/App.tsx, src/components/content/observations/helpers/bubble.tsx, src/components/content/observations/helpers/columns.tsx, src/components/content/observations/helpers/observations-table.tsx, src/fhir/models/observation.ts
This PR updates the observation table in the drawer. 
CTW-1035
=> Observation Drawer

.changeset/tricky-dodos-fix.md, src/components/content/observations/helpers/columns.tsx, src/components/content/observations/helpers/details.tsx, src/components/content/observations/observations-details.tsx, src/fhir/diagnostic-report.ts, src/fhir/models/observation.ts, src/utils/nodash/index.ts
This PR cleans up the labs drawer with the feedback obtained after QA.
=> Labs cleanup

.changeset/healthy-crabs-change.md, src/fhir/models/document.ts
The documentRef resource was deduping slightly wrong as the managingOrganization was not showing up so added that back for FQS.
=> Fix document managingOrg

.changeset/stupid-fireants-burn.md, src/services/fqs/long-poll-fqs.ts
Adds a metric to track FQS latency across all resource types. Please merge upon approval.
=> CTW-1185 longpoll metric

.env.example, src/fhir/search-helpers.ts
This can help in debugging discrepencies between ODS and FQS.
=> Add ENV var to fetch all pages from ODS

.changeset/small-poets-thank.md, package-lock.json, src/components/content/allergies/helpers/history.tsx, src/components/content/allergies/patient-allergies.tsx, src/components/content/care-team/patient-careteam.tsx, src/components/content/conditions/helpers/details.tsx, src/components/content/conditions/helpers/history.tsx, src/components/content/document/patient-documents.tsx, src/components/content/immunizations/patient-immunizations.tsx, src/components/content/observations/helpers/details.tsx, src/components/content/resource/history.ts, src/components/content/resource/resource-details-drawer.tsx, src/components/content/timeline/helpers/modal-hooks.tsx, src/fhir/models/document.ts, src/fhir/models/fhir-model.ts, src/fhir/provenance.ts, src/services/fqs/queries/provenances.ts
CTW-690
Fetching from FQS is currently disabled until FQS supports provenance queries for all resource types AND back fills provenance data.
=> Setup fetching provenances from FQS (disabled)

.changeset/pretty-peaches-lie.md, src/App.tsx, src/components/content/allergies/patient-allergies.stories.tsx, src/components/content/allergies/patient-allergies.tsx, src/fhir/allergies.ts
https://zeushealth.atlassian.net/browse/CDEV-210
Allergies component no longer reads whether or not FQS is enabled a property; now fetches toggle directly from Unleash
=> CDEV-210: Update Allergies components to read FQS feature flags directly from Unleash

.changeset/wet-days-explain.md, src/services/fqs/queries/allergies.ts, src/services/fqs/queries/conditions.ts, src/services/fqs/queries/fragments.ts, src/services/fqs/queries/medication-statements.ts
Adds text to codeable concepts in queries.
=> Add text to codeable concepts in queries

.changeset/breezy-students-think.md, src/components/content/document/patient-documents.tsx, src/fhir/document.ts
https://zeushealth.atlassian.net/browse/CDEV-211
=> CDEV-211: Updating usePatientDocument hook to fetch feature flag from Unleash directly

.changeset/pink-impalas-bow.md, src/fhir/medications.ts
Use a separate toggle variant from the medications table requests
=> update medications history drawer to use a separate toggle variant

.changeset/shy-cooks-sin.md, src/App.tsx, src/components/content/immunizations/patient-immunizations.stories.tsx, src/components/content/immunizations/patient-immunizations.tsx, src/fhir/immunizations.ts
https://zeushealth.atlassian.net/browse/CDEV-220
=> CDEV-220: Updated Immunizations component list view to pull feature flags directly from Unleash

.changeset/tidy-gifts-smell.md, src/fhir/medications.ts, src/fhir/search-helpers.ts, src/fhir/system-urls.ts
switch from using the lens|ActiveMedication tag to the summary|Common tag
=> CDEV-56: update medication lens query to use the summary|Common tag

.changeset/funny-toes-visit.md, src/components/content/allergies/helpers/history.tsx, src/components/content/conditions/helpers/history.tsx, src/components/content/medications/helpers/history.tsx, src/components/content/resource/history.ts, src/components/content/resource/resource-details-drawer.tsx
This PR adds a useHistory variant to useHistory hook for enabling/disabling FQS in the drawer
=> Update use history variant

.changeset/brave-olives-brake.md, src/fhir/care-team.ts, src/services/fqs/queries/care-teams.ts
This PR rewires the CareTeam resource to FQS.
=> Rewire Careteam to FQS

.changeset/sweet-chicken-help.md, src/fhir/provenance.ts
This PR fixes the provenance query.
=> Fix provenance query

src/api/urls.ts, src/services/fqs/client.ts
Also use it for routing requests to FQS via the new URLs.
=> INFR-626 Create a new function in `urls` that constructs a service-name based URL

.changeset/smooth-dingos-design.md, src/components/core/providers/feature-flag-provider.tsx
CDEV-250
This works in conjunction with adding a new "hostname" context field to unleash for feature flagging.
=> CDEV-250/add url to unleash context

.changeset/funny-ladybugs-hunt.md, src/services/fqs/queries/medication-request.ts
Update FQS query for medication requests to expand the prescriber reference
=> CDEV-246: med request prescriber

.changeset/lemon-ants-search.md, src/services/fqs/queries/medication-request.ts
Pull the dispense request performing organization in medication request FQS query
=> Fix CDEV-258 prescription ordered missing pharmacy

.changeset/proud-avocados-fly.md, src/App.tsx, src/fhir/provenance.ts, src/services/fqs/queries/fragments.ts
This PR addresses the drawer issue with CareTeams and also fixes a couple data discrepancies.
=> Fix a couple data disparities in CareTeams

.changeset/poor-buckets-march.md, src/components/core/unread-notification.tsx
In the standalone app we sometimes need to change the color of this icon so adding a classname input.
=> CTW-1282 Add className input for UnreadNotification icon

.changeset/wise-onions-obey.md, src/index.ts
Forgot to add this component to exports in previous PR.
=> CTW-1282 Adding unread documents component to exports

.changeset/green-houses-wonder.md, src/components/content/document/helpers/filters.ts
=> Add encounter date to dedupe document logic

.changeset/big-tigers-marry.md, src/services/fqs/client.ts
CDEV-282
This PR adds the request header for all FQS requests.
=> Add request headers

.changeset/swift-vans-dress.md, src/App.tsx, src/components/content/medications/helpers/columns.tsx, src/components/content/resource/helpers/resource-title-column.tsx, src/fhir/medications.ts, src/hooks/use-medications.ts
Fixing queries for medications to look more like conditions and support read/dismiss functionality. Tested against existing components for backwards compatibility. Also fixed issue where we shouldn't mess with the capitalization of medication display names.
=> CTW-1279 Meds read/dismiss fix and capitalization change

.changeset/shy-coats-kiss.md, src/components/content/conditions/patient-conditions-all.tsx, src/components/content/medications/patient-medications-all.tsx
Updating the new conditions all and medications all components to use the new empty state
=> Add empty state to new conditions and meds components

.changeset/yellow-parrots-agree.md, src/components/content/diagnostic-reports/helpers/diagnostic-report-query-filters.ts, src/fhir/diagnostic-report.ts
CDEV-289
This PR adds dedupe logic to dedupe for FQS and ODS. Confirmed with the patient attached in the ticket
=> Add dedupe logic for diagnostic reports

.changeset/shiny-doors-cover.md, src/components/core/providers/ctw-provider.tsx, src/components/core/providers/patient-provider.tsx
Need these types for setting up standalone ZAP in a separate repo.
=> CTW-1293 Export types for CTWProviderProps and PatientProviderProps

.changeset/chilly-lions-talk.md, src/components/content/observations/helpers/columns.tsx
https://zeushealth.atlassian.net/browse/CDEV-293
=> CDEV-293: Adding bold to trend value (to match date)

.changeset/shaggy-plums-jump.md, src/fhir/observations.ts
This PR adds the metric to count zero moments for setting up the DD dashboard.
=> Update DD metrics for labs

.changeset/lemon-masks-pretend.md, src/fhir/observations.ts
https://zeushealth.atlassian.net/browse/CDEV-290
=> CDEV-290: Resolving issue where empty filter makes request invalid

.changeset/spicy-buses-rest.md, src/components/content/diagnostic-reports/helpers/columns.tsx, src/fhir/models/diagnostic-report.ts
=> Swap performer with number of results available for diagnostic reports

.changeset/happy-chefs-repeat.md, src/fhir/observations.ts
https://zeushealth.atlassian.net/browse/CDEV-268
Updating Observation FQS query to filter by system in addition to code, which removes the need to frontend filter.
=> CDEV-268: Updating Observations query to filter by system/code

.changeset/forty-ties-wash.md, src/api/urls.ts
Update metrics URL to use the new app.zushealth.com url
=> CTW-911/app.zushealth.com

.changeset/spotty-pots-unite.md, src/components/content/allergies/patient-allergies.tsx, src/components/content/conditions/patient-conditions-all.tsx, src/components/content/diagnostic-reports/patient-diagnostic-reports.tsx, src/components/content/document/patient-documents.tsx, src/components/content/immunizations/patient-immunizations.tsx, src/components/content/medications/patient-medications-all.tsx, src/components/content/observations/helpers/details.tsx, src/components/content/patient-history/patient-history-message.tsx, src/components/content/patient-history/patient-history-table.tsx, src/components/content/patients/patients-table.tsx, src/components/content/resource/helpers/details-card.tsx, src/components/content/resource/helpers/history-entry.tsx, src/components/content/resource/helpers/history.tsx, src/components/core/drawer.tsx, src/components/core/modal-confirm-delete.tsx, src/components/core/pagination/pagination.tsx, src/components/core/pagination/simple-pagination.tsx, src/components/core/table/table-head.tsx, src/components/core/table/table.tsx, src/utils/telemetry.ts
A little additional cleanup to go with PR https://github.com/zeus-health/ctw-component-library/pull/1005
=> CTW-290/removing telemetry namespace

.changeset/shy-eggs-fetch.md, src/components/content/zus-aggregated-profile/zus-aggregated-profile-tabs.tsx
https://zeushealth.atlassian.net/browse/CDEV-263
=> CDEV-263: Removed beta label from Diagnostic Report tab in ZAP

.changeset/smooth-candles-scream.md, src/components/content/patient-history/patient-history-last-retrieved.tsx
=> Display records never requested

.changeset/fuzzy-dogs-invite.md, src/components/content/observations/helpers/columns.tsx
CDEV-290
This PR tries to fix the telemetry not showing up.
=> Diagnostic Trend Click Count

.changeset/shaggy-ladybugs-care.md, src/components/content/observations/helpers/columns.tsx, src/components/content/observations/helpers/observations-table.tsx, src/components/content/resource/resource-table.tsx, src/components/core/table/table.tsx
CDEV-323
This PR removes the load more from the DR drawer.
=> Ctw 323/remove show all

.changeset/fresh-dogs-sort.md, src/components/content/diagnostic-reports/helpers/columns.tsx, src/components/content/diagnostic-reports/helpers/diagnostic-report-query-filters.ts, src/components/content/observations/helpers/details.tsx, src/components/content/observations/helpers/drawer.tsx, src/fhir/diagnostic-report.ts, src/fhir/models/diagnostic-report.ts
https://zeushealth.atlassian.net/browse/CDEV-322
=> CDEV-322: Showing indicator in Diagnostic Report list results

.changeset/modern-ants-shake.md, src/fhir/models/diagnostic-report.ts, src/fhir/models/observation.ts
CDEV-286
This PR adds trends to selected Lipid Panels.
=> Ctw 286/lipid trends

.changeset/giant-fishes-judge.md, src/components/content/diagnostic-reports/diagnostic-reports.scss, src/components/content/diagnostic-reports/helpers/columns.tsx, src/components/content/diagnostic-reports/patient-diagnostic-reports.tsx
https://zeushealth.atlassian.net/browse/CDEV-322
Updating trending indicator in Diagnostics Report table to show on the same line as "details" on smaller screens.
=> CDEV-322:  Updated trending indicator display on small breakpoints

.changeset/stupid-kangaroos-yawn.md, src/components/content/observations/helpers/observations-table.tsx, src/components/content/resource/resource-table.tsx, src/components/core/table/table.tsx
Added a UseEffect to make sure the show all is only rendered after the records length is 0
=> Fix Show All 

.changeset/stupid-onions-build.md, src/fhir/formatters.test.ts, src/fhir/formatters.ts, src/fhir/models/observation.ts, src/fhir/observations.ts, src/services/fqs/queries/fragments.ts, src/services/fqs/queries/observations.ts
Refactored observation request to use existing fragment. Added some formatters and added support for them in `observation.value`.
=> Minor observation fixes

.changeset/chatty-falcons-sniff.md, src/fhir/models/observation.ts
This PR adds more loinc codes for the trending feature.
=> Add missing codes plus glomeluar filtration

.changeset/popular-peaches-yawn.md, src/components/content/timeline/helpers/filters.tsx, src/components/content/zus-aggregated-profile/zus-aggregated-profile-tabs.tsx, src/components/core/filter-bar/filter-bar-types.ts, src/fhir/models/timeline-event.ts
This PR removes beta label from timeline.
=> Remove beta label from timeline

.changeset/poor-sheep-sort.md, src/fhir/models/diagnostic-report.test.ts, src/fhir/models/diagnostic-report.ts, src/fhir/system-urls.ts
https://zeushealth.atlassian.net/browse/CDEV-310
No longer including incorrectly coded glucose observations as part of the trends
=> CDEV-310: Filtering out incorrectly coded glucose trends

.changeset/quick-beers-jog.md, src/fhir/models/observation.ts
Enables more labs for trending feature
=> Enable more labs for trending feature

src/App.tsx, src/components/content/encounters/helpers/columns.tsx, src/components/content/encounters/helpers/filters.tsx, src/components/content/encounters/helpers/modal-hooks.tsx, src/components/content/encounters/helpers/sorts.ts, src/components/content/encounters/patient-encounters.stories.tsx, src/components/content/encounters/patient-encounters.tsx, src/components/content/encounters/story-helpers/mocks/encounters-fqs.ts, src/components/content/encounters/story-helpers/mocks/encounters.ts, src/components/content/encounters/story-helpers/mocks/medication-statement.ts, src/components/content/encounters/story-helpers/mocks/patient.ts, src/components/content/encounters/story-helpers/mocks/provenances.ts, src/components/content/encounters/story-helpers/mocks/requests.ts, src/components/content/zus-aggregated-profile/zus-aggregated-profile-tabs.tsx, src/components/content/zus-aggregated-profile/zus-aggregated-profile.tsx, src/components/core/simple-more-list.tsx, src/fhir/models/document.ts
=> CDEV-352 create new encounters component and remove timeline from ZAP

.changeset/forty-items-grab.md, .env.example, .storybook/preview.jsx, package-lock.json, src/App.tsx, src/api/urls.ts, src/components/content/observations/helpers/columns.tsx, src/components/content/zus-aggregated-profile/zus-aggregated-profile-iframe.tsx, src/components/content/zus-aggregated-profile/zus-aggregated-profile.tsx, src/components/core/providers/ctw-context.tsx, src/components/core/providers/ctw-provider.tsx, src/components/core/providers/telemetry/context.ts, src/components/core/providers/telemetry/telemetry-provider.tsx, src/components/core/providers/telemetry/use-telemetry.ts, src/components/core/providers/theme/context.ts, src/components/core/providers/theme/theme-provider.tsx, src/components/core/providers/theme/use-theme.ts, src/components/core/providers/use-ctw.ts, src/components/core/tab-group/tab-group.scss, src/components/core/tab-group/tab-group.tsx, src/hooks/use-breakpoints.ts, src/index.ts, src/styles/tailwind.theme.ts, src/utils/telemetry.ts
First iteration on `ZusAggregatedProfileIframe` that takes in the same props as `ZusAggregatedProfile` along with a few additional/optional props to specify the iframe ID/height/width. This loads the hosted ZAP in an iframe with the same config already setup through `CTWProvider` and `PatientProvider`, including themes and internationalization. 
https://github.com/zeus-health/ctw-component-library/assets/97455910/cc9c9388-e531-4859-826b-d5f3916178e5
=> CTW-1293 Setting up ZusAggregatedProfileIframe component

.changeset/wild-colts-tickle.md, src/App.tsx, src/components/content/zus-aggregated-profile/zus-aggregated-profile-iframe.tsx
Renamed `ZusAggregatedProfileIframe` to `ZusAggregatedProfileIFrame`
=> CTW-1293/minor nit - rename Iframe to IFrame

.changeset/chatty-parrots-clap.md, src/components/content/document/helpers/filters.ts, src/components/content/resource/resource-details-drawer.tsx
=> Cdev 292 dont show unrenderable source documents

.changeset/thirty-teachers-joke.md, src/components/content/document/helpers/filters.ts, src/components/content/resource/resource-details-drawer.tsx
Reverts zeus-health/ctw-component-library#1079
=> Revert "Cdev 292 dont show unrenderable source documents"

.changeset/thin-ligers-hear.md, src/components/content/allergies/helpers/history.tsx, src/components/content/conditions/helpers/history.tsx, src/components/content/resource/history.ts, src/components/core/providers/patient-provider.tsx, src/fhir/allergies.ts, src/fhir/care-team.ts, src/fhir/diagnostic-report.ts, src/fhir/document.ts, src/fhir/encounters.ts, src/fhir/immunizations.ts, src/fhir/medications.ts, src/fhir/observations.ts, src/fhir/search-helpers.ts, src/hooks/use-medications.ts, src/services/conditions.ts
CDEV-330
Note to Reviewer: Please run my branch locally to test and **DO NOT MERGE** immediately after approval.
This PR removes ODS related queries and functions for the resources we have setup.
=> Remove ODS code path for UPID-based queries

.changeset/gold-plants-divide.md, src/components/content/encounters/helpers/modal-hooks.tsx
=> CDEV-317 Update date range and remove type field for encounters details drawer

.changeset/tough-paws-relate.md, src/components/content/encounters/helpers/columns.tsx, src/fhir/models/encounter.ts, src/services/fqs/queries/fragments/encounter.ts
This PR adds the speciality for the provider using the location field.
=> CDEV-321/Add speciality for the provider using location

.changeset/young-suits-learn.md, src/index.ts
Export Resource Table Actions component
=> export resource table-actions

.changeset/neat-mirrors-glow.md, src/fhir/encounters.ts
Resolved issue with encounters showing "no data" before data was requested
=> Fixing encounters loading state issue

.changeset/two-months-exist.md, src/fhir/formatters.test.ts, src/fhir/formatters.ts
=> fix: address filtering 0 as an invalid quantity or age

.changeset/wild-cows-complain.md, src/components/content/zus-aggregated-profile/zus-aggregated-profile.scss, src/components/content/zus-aggregated-profile/zus-aggregated-profile.tsx, src/components/core/main.scss, src/components/core/providers/theme/theme-provider.tsx
Add 100 percent height to fix height issue in iframe.
=> Ctw 1352/iframe height issue

.changeset/clean-stingrays-travel.md, src/App.tsx, src/components/content/table/patient-adt-alerts-table.tsx, src/fhir/encounters.ts, src/fhir/search-helpers.ts, src/utils/query-keys.ts
This PR adds a prototype table for ADT alerted patients that are currently in the hospital.
=> CDEV-373/prototype adt alerts

.changeset/strange-snakes-yawn.md, src/components/content/table/patient-adt-alerts-table.tsx, src/index.ts
This PR exports the new adt table
=> Export new table

.changeset/hot-rockets-smell.md, src/App.tsx, src/components/content/table/patient-adt-alerts-table.tsx
This PR removes setting the ADT information via ODS and now wire it via getting the info via Snowflake.
=> Removing ODS and adding support for obtaining data via Snowflake

.changeset/selfish-planets-perform.md, src/components/content/patient-history/patient-history-last-retrieved.tsx, src/fhir/models/patient.ts
=> fix: hide requests not found for test patients

.changeset/warm-coins-peel.md, src/App.tsx, src/components/core/modal-confirm-delete.tsx, src/i18n/index.ts
=> Fixing display of delete confirmation modal

.changeset/neat-dolphins-retire.md, src/fhir/models/index.ts
This PR exports encounterModel.
=> Export encounterModel

.changeset/brave-days-notice.md, src/components/content/encounters/helpers/filters.test.ts, src/components/content/encounters/helpers/filters.tsx, src/components/content/patients-adt/patients-adt-alerts-table.tsx, src/fhir/encounters.ts
=> Add deduping for ADT alerts

.changeset/mean-parents-poke.md, src/components/content/patient-record-search/patient-record-search.tsx, src/components/content/zus-aggregated-profile/zus-aggregated-profile.tsx
Wraps SearchPatientRecords form handler in useCallback
=> SearchPatientRecords form to use useCallback

.changeset/cool-windows-speak.md, src/components/content/patient-record-search/patient-record-search.tsx
Fixing error state in search component.
=> CTW-1380 Fixing error state

.changeset/tall-tomatoes-accept.md, src/components/content/zus-aggregated-profile/zus-aggregated-profile-iframe.tsx
Add letterSpacing and fontWeight to iframeTheme Props
=> Add configurability to iframe props

.changeset/wise-numbers-remain.md, src/components/content/patients-adt/filters.ts, src/components/content/patients-adt/patients-adt-alerts-table.tsx
This PR sets the filtering up for the ADT table for Active vs Discharged
=> Filter for ADT Table

.changeset/wise-rings-fold.md, src/components/content/patients-adt/modal-hooks.tsx, src/components/content/patients-adt/patients-adt-alerts-table.tsx
CDEV-470
This PR adds ability to add row actions (read and dismiss records) and bolds unread records.
=> Attempt at adding read/dismiss notifications

.changeset/healthy-penguins-lick.md, src/components/content/patients-adt/filters.ts
This PR adds the dismiss filter feature in our filters.
=> Add adt dismiss filter

.changeset/eleven-apes-attend.md, src/components/content/patients-adt/patients-adt-alerts-table.tsx
=> Fix casing

.changeset/smart-tomatoes-glow.md, src/components/content/patients-adt/patients-adt-alerts-table.tsx
Reverts zeus-health/ctw-component-library#1287
=> Revert "Fix casing"

.changeset/tall-kiwis-shake.md, src/components/content/patients-adt/patients-adt-alerts-table.tsx
CDEV-521
This fixes the notification hover actions that are missing in the ADT table.
=> fix functionality

.changeset/pretty-chefs-deliver.md, src/components/content/patients-adt/modal-hooks.tsx, src/components/content/patients-adt/patients-adt-alerts-table.tsx
Revert version .6 and make a small style change.
=> Remove notification hover actions for now b/c broken

.changeset/rare-mails-remain.md, package-lock.json, src/App.tsx, src/components/content/overview/patient-overview.tsx, src/components/content/patient-record-search/patient-record-search.tsx, src/components/content/resource/helpers/view-button.tsx, src/components/content/resource/resource-table-actions.tsx, src/components/core/filter-bar/filter-bar.tsx, src/components/core/sort-button/sort-button.tsx
The commits should line up with the various changes if you prefer to view changes commit by commit.
https://www.loom.com/share/81d06bf24def435693b314c3b9685ac8?sid=ddf8b4c6-3e2b-496e-8df2-46e8cadca461
=> CTW-1364/UI changes for viewing at various sizes

.changeset/breezy-terms-dress.md, src/components/content/patients-adt/modal-hooks.tsx, src/components/content/patients-adt/patients-adt-alerts-table.tsx, src/fhir/allergies.ts, src/fhir/basic.ts, src/fhir/diagnostic-report.ts, src/fhir/document.ts, src/fhir/encounters.ts, src/fhir/immunizations.ts, src/hooks/use-filtered-sorted-data.ts
Revert request for basics due to bug
=> Revert ADT basics

.changeset/fluffy-waves-collect.md, src/index.ts
Jira Ticket Number: none
Exports `RelatedEncounter` type so that we can use it in CTW.
I didn't.
I will try to import it in CTW.
=> Add RelatedEncounters to exports

.changeset/hungry-cats-marry.md, package-lock.json, src/services/fqs/queries/allergies.ts, src/services/fqs/queries/diagnostic-reports-query.ts, src/services/fqs/queries/fragments/condition.ts, src/services/fqs/queries/immunizations.ts
Jira Ticket Number: CTW-1564
Fixes FQS queries that were broken when updating branch from main.
Tested locally.
Will get tested along with the next version bump in CTW.
=> CTW-1564 Fix broken FQS queries
