.github/workflows/release.yaml
.github/workflows/validate.yml

Trying to follow https://github.blog/changelog/2022-09-08-github-actions-use-github_token-with-workflow_dispatch-and-repository_dispatch/
I believe:
1. Adding `workflow_dispatch` to the validate workflow should at least make it available to be manually run.
2. Trying to get the release workflow to trigger the validate workflow.

Attempting to enable CI for changeset PRs

---

src/components/content/conditions-history-drawer.tsx
src/components/content/conditions-history.tsx
src/components/content/conditions.tsx
src/models/conditions.ts

This PR adds fetching by icd10 or snomed and if there are both it displays both in the condition history drawer. First search is by icd10.

Edit Condition History to show both of them

---

.changeset/rich-pets-refuse.md
src/components/content/condition-form-drawer.tsx
src/components/content/conditions-history.tsx
src/fhir/search-helpers.ts

This resets the state so if you view condition A and then click on condition B, it doesn't show you condition A.

Bugfix - reset the state after viewing condition

---

.changeset/seven-cats-join.md
src/components/content/conditions-table-base.tsx

Recalculated the Condition table column width classes to total 100% to prevent confusion. This will not impact how the table is viewed.

CTW-327 Followup: Condition Table Column Width Patch

---

.changeset/gentle-clouds-travel.md
.eslintrc.cjs
src/hooks/use-breakpoints.ts
src/hooks/use-isomorphic-layout-effect.ts

This fixes an issue with SSR.
> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
Followed https://medium.com/@alexandereardon/uselayouteffect-and-ssr-192986cdcf7a for work around.

Don't use useLayoutEffect directly

---

.changeset/smooth-kiwis-dream.md
package-lock.json
package.json
src/fhir/client.ts
src/fhir/search-helpers.ts
src/fhir/system-urls.ts

Components that were meant to display only records owned by the builder now address the case of shared records between builders. Rather than filtering out by non-builder tags, the query filters for the ownership tag of the specific builder.

CTW-333: Filter out non-builder records using the builder ID in the JWT

---

.changeset/dirty-pandas-dream.md
src/components/content/conditions-history-drawer.tsx
src/components/content/conditions-history.tsx
src/components/core/ctw-provider.tsx
src/fhir/conditions.ts
src/fhir/search-helpers.ts
src/fhir/system-urls.ts
src/models/conditions.ts

Manage inconsistent coding in Conditions History Panel. Now supports SNOMED, ICD-10, ICD-10CM, ICD-9, ICD-9CM for code matching. Will now filter out summary and lens tags as well. Also now uses react query for history searches for faster performance when going back to already visited history searches.

Ctw 354/manage inconsistent coding in history panel

---

.changeset/purple-parents-jog.md
src/components/core/ctw-context.tsx
src/components/core/ctw-provider.tsx

Moving the CTW Context and provider into separate files to avoid issues when changing certain files it errors out and  says context is not defined. This is caused by a bug in vite which there is a current open pr on.. https://github.com/vitejs/vite/pull/10239, which should solve this. Being that this bug is annoying enough in dev i am splitting context and provider into separate files to avoid this bug.

move context out of provider file to avoid refresh bug

---

.changeset/gold-bears-shop.md
src/components/core/collapsible-data-list.tsx

This PR fixes the spacing between detail and summary card.

Condition History Detail and Summary Spacing fix

---

.changeset/breezy-cobras-remember.md
src/fhir/conditions.ts

Alphabetize conditions primarily by CCS grouping and secondarily the condition name so that users can quickly find the conditions by their category.
Example:

Primarily alphabetize by CCS Grouping

---

.changeset/dull-taxis-attack.md
src/components/content/conditions-history.tsx

This PR just updates sorting for the history panel page to now sort by date and then move the empty dates to the end.

Add sorting to condition history page

---

.changeset/quiet-eyes-buy.md
src/components/content/conditions-history.tsx
src/components/core/collapsible-data-list.tsx

This PR adds a separate section for records with no date. If there is no entry, then no section will show up. 
With Both Date and No Date: 
With only Dates:
With only no Dates:

Add Records with no date in a separate format in condition history

---

.changeset/stupid-moose-warn.md
src/App.tsx
src/components/content/forms/drawer-form-with-fields.tsx
src/components/core/ctw-context.tsx
src/components/core/ctw-provider.tsx
src/components/core/drawer.tsx
src/components/core/dropdown-menu.scss
src/components/core/dropdown-menu.tsx
src/components/core/main.scss
src/styles/tailwind.theme.ts

* Added manual headlessui-portal-root to get drawer added within CTWProvider which defines theme CSS vars.
* Added a CTWProviderRef to the useCTW context and explicitly told dropdown-menu to use that for portal placement.
* Added custom theme example to App.tsx
* Fixed a few minor theming issues with colors in a few spots.

Fix theming issue with drawer + dropdown menu

---

.changeset/weak-yaks-hear.md
src/fhir/search-helpers.ts
src/fhir/system-urls.ts

When a patient exists across multiple builders lens output is written redundantly across all of those builders. When the Common Patient Record (CPR) is enabled (as it is in dev) this is causing all of those redundant lens resources to be returned. A simple fix for this in the immediate term is to update the lens requests to additionally filter by the caller’s builder.

CTW-418 Add builder filter to lens request

---

.changeset/five-peas-live.md
src/components/content/conditions-history.tsx
src/components/content/conditions.tsx
src/fhir/formatters.ts
src/models/conditions.ts

This PR updates the condition history panel with a few updates: 
1. Sorts the history panel by date (starting with year, month, then day) and Records with no Date is left aligned
2. Categories relabeled to Category
3. takes any date in the yyyyMMDDetc... format and converts into MM/DD/YYYY format.

Condition updates to the history panel

---

.changeset/four-shirts-hide.md
src/components/content/conditions-table-base.tsx
src/components/content/conditions.tsx
src/components/content/forms/drawer-form-with-fields.tsx
src/utils/form-helper.ts

This PR removes the fill out the field tooltip and adds aria-required attribute to the form fields that are required.
Also: fixed hidemenu to reflect readonly for the meatball menu when it is present in App.tsx

Add aria-required attribute to the form fields

---

.changeset/red-sloths-melt.md
src/components/core/pagination/pagination.tsx
src/components/core/table/table.tsx

Ticket: [CTW-406](https://zeushealth.atlassian.net/browse/CTW-406)
Figma: [pagination](https://www.figma.com/file/PMFiTmKkExhuPjpInXjrp3/Implementation-(Healthie)?node-id=2164%3A2950)
There are 4 use cases to be tested:
1. For <=10 Conditions - no pagination
2. For >10 Conditions - Show All button
3. For >20 Conditions - Show More button (next 10 conditions shown) and Show All button
3. For all >10 conditions shown - Reset button (first 10 conditions shown)
1st, 2nd, and 4th use cases (`patientId: dad67efb-749f-47d7-9600-7f24f33dcc94`):
https://user-images.githubusercontent.com/86961468/196726084-7fe5c587-c7f6-4497-87a1-ab4841e3baba.mov
3rd  use case (`patientId: 8ba07acb-0dac-450e-911d-3609d9b51a4b`):
https://user-images.githubusercontent.com/86961468/196725960-d12a807d-b7bb-4cdc-a971-8dc …

[CTW-406] Add pagination component

---

.changeset/fair-rabbits-cough.md
src/components/content/conditions-table-base.tsx

[CTW-365](https://zeushealth.atlassian.net/jira/software/projects/CTW/boards/49?selectedIssue=CTW-365)
This PR updates the column header names in both tables.

CTW-365/update names

---

.changeset/calm-experts-speak.md
src/components/core/form/combobox-field.tsx

No longer get the the error that you need to select a condition name when you have selected one.

Fix Condition Name Selector

---

.changeset/early-suns-fly.md
src/fhir/conditions.ts

This PR fixes the sort to move null to the bottom and sort by alphabetical order and sorts by year first.

Update sort by year and then move null to bottom

---

.changeset/khaki-peas-switch.md
src/components/content/forms/conditions.ts

Fix the condition form to let users set a condition's verification status to "entered-in-error".
https://user-images.githubusercontent.com/33408946/199092912-8c15681f-16bf-4e38-be9a-6d5a4384923d.mov

Entered-in-error Status

---

.changeset/gold-ways-exercise.md
src/components/content/forms/conditions-autocomplete.tsx
src/components/core/ctw-provider.tsx
src/components/core/form/combobox-field.tsx

This fixes a bug where our condition autocomplete was grabbing the `authToken` from `getCTW`. This auth token was only set if the app passed in `authToken` to `CTWProvider`. Instead, everything should go through the `getRequestContext` which will correctly grab and ensure a non-expired authToken.
Additionally:
* Persist autocomplete search event as the use of debounce causes react to garbage collect the event.
* Add an `isLoading` to fix a bug where autocomplete would briefly say no results found while the search was running.

CTW-491/fix condition autocomplete

---

.changeset/twenty-brooms-hang.md
src/components/content/forms/conditions.ts
src/fhir/formatters.ts

[CTW-475
](https://zeushealth.atlassian.net/jira/software/projects/CTW/boards/49?selectedIssue=CTW-475)
This PR updates the onset date functionality to not just set directly to today's date if there is no onset date provided. 
https://user-images.githubusercontent.com/98342697/199324597-8db92221-01e3-4f59-a279-855e5e187346.mov

Ctw 475/onset date update

---

.changeset/quick-rivers-leave.md
src/fhir/system-urls.ts

This just updates the system url for aggregated from `"http://zusapi.com/lens/extension/aggregatedFrom"` to `"https://zusapi.com/lens/extension/aggregatedFrom"` in order to match what is used in upi-service

Update lens extension "aggregated from" system url

---

.changeset/slimy-moose-hide.md
src/components/content/forms/condition-schema.tsx
src/components/content/forms/drawer-form-with-fields.tsx
src/components/content/forms/form-field.tsx
src/components/core/main.scss

CTW-506
- If notes is populated it will now show when editing a condition (This should also happen when adding from other patient records - have to confirm if we want this). Notes can only be resized vertically now.

Ctw 506/show notes previous text when editing

---

.changeset/honest-plants-camp.md
package-lock.json
src/index.ts
src/models/index.ts

Exporting parts of the library that would be used if someone were building custom components using the library. Currently it is difficult to build a custom medication table and drawer like `<PatientMedications />`  because we don't export some of the useful building blocks of the library.
It's possible that future refactors might make some of these exports obsolete, but if that's the case we should just version bump accordingly.

Export drawer from index

---

.changeset/eleven-eels-try.md
src/fhir/medications.ts

Adding de-duping logic to medication history so that we only show 1 record per date. This logic takes the first record per date, so it's possible we'll be choosing a record that has less useful information than another, but we can address that as it comes up during troubleshooting. This seems like a reasonable first step, especially as we saw so many dupes in early production tests that the history was hard to make sense of.
Screenshot with dupes
Screenshot after change

CTW- 533 De-dupe med history

---

.changeset/fast-spiders-rush.md
src/components/content/conditions.tsx
src/components/core/ctw-provider.tsx
src/components/core/form/combobox-field.tsx
src/components/core/main.scss
src/components/core/table/table-full-length-row.tsx
src/components/core/table/table-rows.tsx
src/styles/tailwind.theme.ts
src/utils/types.ts
src/utils/typescript.ts

* Change how empty table message gets centered
* Put empty CSS vars in CTWProvider's div style
* Autocomplete changes
* Make autocomplete use absolute positioned options.
* Make autocomplete reopen when clicking in the input box.
Autocomplete with floating options

CTW-522/css issues

---

.changeset/plenty-toes-taste.md
src/components/content/conditions-history.tsx

[CTW-539](https://zeushealth.atlassian.net/jira/software/projects/CTW/boards/49?selectedIssue=CTW-539)
This PR filters entered-in-error for verification status from condition history panel. 
Before: 
After:

Filter entered-in-error from condition history

---

.changeset/pink-hairs-call.md
src/components/content/conditions-history.tsx
src/components/content/medication-drawer.tsx
src/components/content/medication-history.tsx

Capitalizing various fields in the details/history drawers. I figured there was 3 options here: 
1. Do it generically in the underlying core components with something like a `capitalize` boolean prop
2. Do it in the getters
3. Do it when setting up data to pass to the component for presentation
I chose option 3 because it felt like this kind of decision belongs close to the presentation layer. The underlying data may not be capitalized, and this is likely a case-by-case decision (eg. we're not going to capitalize the "h" at the beginning of a URL), so I thought this was the appropriate place to put this logic.
https://user-images.githubusercontent.com/97455910/200661327-a865a375-0b9a-498b-a996-4b35cd27ae10.mov

CTW-349 Capitalizing fields in details/history drawer

---

.changeset/rude-items-hear.md
src/components/content/conditions.tsx

CTW-543
Clicking add condition from other provider records after clicking edit condition does not result in an error anymore.

Ctw 543/fix edit add condition bug

---

.changeset/tame-spies-tell.md
src/fhir/search-helpers.ts

We originally fixed an issue with dupes showing up from lens requests when CPR is turned on via this commit - https://github.com/zeus-health/ctw-component-library/commit/9b0b1ff752a9d9cf165b786c62a1615bda62b0a4.
Then this commit reverted the change - https://github.com/zeus-health/ctw-component-library/commit/bf1013e6c1705ddb908f81863da323023b007c30.
I think that was an oversight when merging. Having proper automated testing would prevent this kind of headache in the future. That said, trying to get this fix back in asap for demos.

CTW-548 Fixing lens query tag filter that got reverted

---

.changeset/gentle-cameras-design.md
package-lock.json
src/components/core/action-list/action-list.scss
src/components/core/action-list/action-list.stories.tsx
src/components/core/action-list/action-list.tsx
src/index.ts

Creates an `<ActionList/>` component which will look something like this:
And in the wild:
Notable attributes:
List items marked "active" will show a (primary) colored border to the left by default and when hovered present a button to take action on that item. Optionally the opposite can be done for inactive items if an `onUndoAction` handler is passed in, but that is not a requirement.
It is the duty of the data owner to set the "active" property on their item through their custom "onAction" handler. The list is simply rendering state and wiring up the event listeners.
There is an optional "onRowClick" handler that will take action if the row is clicked or enter button is pushed while row is focused. It is the responsibility of the code-base utilizing this component to create a style for …

CTW-526/Create ActionList (match canvas UI)

---

.changeset/angry-dryers-boil.md
src/components/content/conditions-history.tsx

Previously we were displaying the code display value which was ending up pretty redundant. Per CTW-544 changing this to display the condition category which is either "Problem List Item" or "Encounter Diagnosis". Essentially distinguishing whether "this visit was to address this Dx" vs "we verified the patient has this condition". 
**Before**
**After**

CTW-544 Changing condition history title to category

---

src/components/core/action-list/action-list.stories.tsx
src/components/core/action-list/action-list.tsx

1. There is no `message` prop so remove it from `argTypes`.
2. Move `export default` to the top as that is the main thing that sets up the stories.
3. Storybook will automatically pass in callback functions which log to the `actions` tab when viewing a single story (see screenshot). So... we need to explicitly set a callback to `undefined` if we want to get rid of it.
4. Any description of the component or of the properties should be in the component code itself and not just the story code. Unfortunately there is a bug right now where this requires a storybook restart to get picked up.

Simplify action list stories

---

.changeset/bright-kings-brush.md
src/components/content/conditions.tsx
src/components/content/conditions/helpers.test.ts
src/components/content/conditions/helpers.ts
src/fhir/conditions.ts
src/models/condition.test.ts
src/models/condition.ts

CTW-518
We now filter out other provider conditions if there are ANY (active or inactive) patient conditions that match and are newer. In order to do this we fetch all conditions.
NOTE: There is currently a bug here if there are more than 250 conditions as that is the max we get from ODS without paging.

CTW-518/filter condition summary resources

---

.changeset/yellow-pears-applaud.md
.storybook/preview.js
src/components/content/conditions.scss
src/components/content/conditions.tsx
src/components/content/conditions/conditions.stories.tsx
src/components/content/conditions/mocks/empty-conditions.ts
src/components/core/main.scss
src/components/core/pagination/pagination.tsx
src/components/core/table/table-full-length-row.tsx
src/components/core/table/table.scss
src/components/core/table/table.tsx

Story changes:
* Add empty conditions story.
* Fix bug where react query was caching mock responses across stories.
* Add a fixed-width prop option for className that will trigger stacked view.
* Setup default values for className and readOnly, this makes the toggles in the storybook actions UI immediately available.
Style fixes -- opted to copy over some styles into conditions.scsss that were previously refactored into main. The goal here is to have isolation within our components by using properly namespaced classes.
* Fixed centering bug for empty stacked tables.
* Fixed pagination whitespace when stacked.
* Fixed bug where bottom border was missing when stacked and showing pagination.
**New empty story and property selections**
**BEFORE** (centering bug)
**AFTER**
**BEFORE** (missing …

More condition stories

---

.changeset/tough-spoons-drum.md
.env.example
src/App.tsx
src/fhir/conditions.ts
src/fhir/medications.ts
src/fhir/search-helpers.ts
src/hooks/use-medications.ts

We are currently displaying "summary medications" which include meds from long ago that the users do not care about and pollutes the UI. We are now going to display "active medications".
Also did some light renaming to help clarify a distinction between "summary" resources and "lens" resources.

CTW-481 Updating meds component to use active meds lens

---

.changeset/nasty-eels-cry.md
src/components/content/conditions-history.tsx
src/components/content/medication-history/index.tsx
src/components/core/collapsible-data-list-stack.tsx
src/components/core/collapsible-data-list.tsx
src/fhir/medications.ts
src/fhir/models/medication-administration.ts
src/fhir/models/medication.ts

- Added this new card for MedicationAdministration resources.
- Created a `fhir/models/medication-administration.ts` to help support this
- Renamed prop `subTitle` to `subtitle`. Verified that in ctw and we aren't explicitly using this `subTitle` prop anywhere. CTW Component Library uses this prop internally to make subtitles on med and condition cards so this change is safe to make

CTW-545/MedicationAdministration card for Med History

---

.changeset/early-dingos-grow.md
src/fhir/models/medication-statement.ts
src/fhir/resource-helper.ts

There was a regression here because `fhir/model/medication.ts` is no longer getting "display" as a fallback from the reference. Additionally, the `lastPrescriber` lens will always be undefined so this also does the work of looking up that prescriber reference.

fix regression in meds component where findReference throws error looking for an unresolvable resource

---

.changeset/forty-lies-walk.md
src/fhir/action-helper.ts
src/fhir/provenance.ts

CTW-558
Provenance now saves which historical version of a resource resulted from an operation, for more thorough tracking of changes. It saves this information as part of the target resource reference.
[Example of a Provenance record this produces](https://fhirplace.dev.zusapi.com/#/Condition/e823c9e5-806d-4fb6-864e-c3ab5e70aa86/show/provenance)

Add version to Provenance target reference

---

.env.example
src/App.tsx

I mistakenly thought the patient ID env var was always the UPID, but clearly there is a system URL input as well.

Reverting patient ID rename in .env

---

src/fhir/models/medication.ts

In the medication history panel, we should be displaying `MedicationStatement.dateAsserted` if available. When it isn’t available - which is not often - we should fall back to `MedicationStatement.effectivePeriod.start`.
---
Example of a broken card
Looking at the underlying resource, it has a date under `MedicationStatement.effectivePeriod.start`

CTW-565/Medication Review (MedicationStatement) date fallback

---

src/components/content/medication-history/index.tsx
src/fhir/models/medication-request.ts

Prescriber and Pharmacy are both missing in several Prescription Ordered cards.
The prescriber was handled in https://zeushealth.atlassian.net/browse/CTW-546
This PR looks up the pharmacy and tries to resolve it in a contained or included resource in the MedicationRequests, then falling back to display text (as it originally was doing).

Medication Request more resilient pharmacy data

---

.changeset/neat-wolves-hear.md
src/components/core/drawer.tsx

This PR makes the bottom border of the top title header inside a `<Drawer/>` span the full width of the drawer. This line delimitates a fixed heading and the remaining scrolling content of the drawer.
Notice the separation between heading/content/footer in the following two images to see the difference 
**Previous:**
**Updated:**
---
Also notice how this looks now where content is under the fixed heading (it more closely resembles how content looks going under the fixed footer)

CTW-552 canvas fit and finish meds drawer heading style

---

.changeset/six-guests-drop.md
src/components/core/action-list/action-list.tsx
src/components/core/drawer.tsx

ActionList had `onAction` as required (at time of creation it made sense) but we found a use-case where the list was used without the action and had to be written as:
```tsx
<ActionList
className="ctw-medication-review-list"
items={actionItems(builderMedications)}
onAction={() => {}}
onRowClick={({ medication }) => openMedicationDrawer(medication)}
actionText=""
/>
```
so this makes `actionText` and `onAction` default to those empty values.
Additionally added `.ctw-drawer-title` to the drawers h2 tag so it can be easily targeted by CSS rules. We found a case where semanticui was messing up the h2 style in an app using ctw-component-library. We don't want to restyle from within, so this classname just makes it easier to target from without.

ActionList doesn't always need action handler

---

.changeset/silent-cats-run.md
src/services/patient-history/patient-history.ts

This PR checks message length as the current API has some issues and makes a decision: 
If any status messages appear in the below API (regardless of content), the component will render as normal (if there are no conditions returned, shows the no condition available). If empty array is returned, we will show the Request Records view.
Data there (Sarah dev):
Data not there (Allen dev):

CTW-471 check message length rather than message status

---

.changeset/short-rats-confess.md
src/fhir/models/condition.test.ts
src/fhir/models/condition.ts

CTW-577
Previously we used `this.clinicalStatus` which uses `codeableConceptLabel` which grabs the `text` field if it exists. The production bug was that this value was `Active` (capitalized). We now go off the actual `code` for the correct `system`. NOTE: Code's here HAVE TO BE lowercase (ODS rejects them otherwise).

Fix bug with detecting active conditions

---

.changeset/dirty-dragons-tap.md
README.md
src/App.tsx
src/components/content/conditions.tsx
src/components/content/patient-history-request-drawer.tsx

- Revert useEffect based on feedback that it is more correct to have `handleClinicalHistory ` called once based on state being undefined. 
- Update readme
- Change logic around showing empty "request records" box in other providers to only show if `clinicalHistoryExists` OR patient has no other provider records.

Minor cleanup

---

src/SecuredApp.tsx

Previously when using the logout button in App.tsx we would see an auth0 error page. This PR changes the `returnTo` value to point at `/login` which is an allowed logout redirect for this app, resulting in the user landing at the auth0 login page for our app.
If in the future we find a use-case where this returnTo path doesn't work we could convert it into an env var.

logout button in App.tsx will now logout

---

.changeset/fuzzy-seahorses-shop.md
src/components/content/forms/medications.tsx
src/components/content/medications/add-new-med-drawer.tsx
src/components/content/medications/medication-history.stories.tsx
src/components/content/medications/other-provider-meds-table.stories.tsx
src/components/content/medications/other-provider-meds-table.tsx
src/components/content/medications/patient-medications.stories.tsx
src/components/content/medications/provider-meds-table.stories.tsx
src/components/content/medications/story-helpers/mocks/other-provider-medications.ts
src/components/content/medications/story-helpers/mocks/provider-medications.ts
src/components/content/medications/story-helpers/mocks/requests.ts
src/components/core/form/drawer-form.tsx
src/fhir/medication.ts
src/fhir/models/medication-statement.ts

Created an "Add to Record" button in the hamburger menu of `<OtherProviderMedsTable/>`.
Added to storybook (based on conditions mocked cache that @WesleyKapow did) so when someone adds an "other provider" med to their record in storybook, that change is updated in their provider meds table. Note: you will only see this happen when looking at the  `<PatientMedications />` story as the `<OtherProviderMedsTable />` story doesn't show the `<ProviderMedsTable />` and the cache doesn't persist story to story.

CTW-621/Add to Record button on other provider meds

---

.changeset/tall-islands-tickle.md
package-lock.json
src/components/content/medications/add-new-med-drawer.tsx
src/fhir/conditions.ts
src/fhir/medications.ts
src/fhir/models/patient.ts

When retrieving the history for a given medication we look up a list of medicationX resources in ODS by ID.
In order to trigger "CPR mode" in ODS, where we surface data across builders, we must search by UPID. This was thought to be a redundant/unnecessary filter, but it is actually required in order to access the data. It's also worth noting that the CPR data is also only available via a search (ie. using the `_id` query parameter) and is not accessible directly by ID.
This does not impact conditions as the condition history fetch is already passing a UPID (see line 122 of `conditions.ts`).

Adding UPID to CPR query

---

src/components/content/medications/helpers.test.ts
src/components/content/medications/helpers.ts
src/components/content/medications/medication-history.tsx
src/components/core/form/drawer-form.tsx

Sort the med history list. For each day, if there is a MedicationRequest that appears exactly at or after the corresponding med dispense then we should shift the order of the MedicationRequest in the history list to come before the dispense.

CTW 582/Prescription Requests should show up before fills

---

.changeset/short-tomatoes-mix.md
package-lock.json
src/fhir/medications.test.ts
src/fhir/medications.ts

Modifying medication filtering logic so that we include medications without an RxNorm code in the builder meds table. Added a unit test for RxNorm filtering function. See video below for manual testing flow using Canvas to create a medication without an RxNorm code (ketamine apparently doesn't have an RxNorm code in Canvas, just an FDB ID).
https://user-images.githubusercontent.com/97455910/209273902-44fdece8-3019-4de2-baba-5142190edb1f.mov

CTW-640 Including meds without an RxNorm code in builder meds table

---

.changeset/perfect-dancers-know.md
src/components/content/forms/schemas/medication-schema.tsx
src/components/content/medications/story-helpers/mocks/requests.ts
src/fhir/models/medication-statement.ts

When adding medication to record from the other provider table:
- Asserted Date will now be set as the current date rather than the original medication statement date asserted.
- The display text is now also properly set on the medication resources `medicationCodeableConcept` value.
- When using "Add to Record" button from Storybook, the mocked response is now intercepting `POST /fhir` rather than `/fhir/MedicationStatement` to reflect that medication statements from this form are now created in a Bundle-transaction.

CTW-638/Add To Record Date and MedicationCodeableConcept text

---

.changeset/wild-birds-attend.md
src/components/core/table/table-rows.tsx
src/components/core/table/table.scss

**Before**
**After** (no more scrollbar)
**Before**
**After** (proper stacked styles)

Fix hover row actions, especially when stacked

---

.changeset/tasty-penguins-compare.md
src/components/content/conditions/conditions.stories.tsx
src/components/content/forms/schemas/medication-schema.tsx

Additional change to #360 to make the date field on the "Add Medication" form be hidden.

CTW-638/Add Medication Form to have hidden date field

---

.changeset/calm-poems-tie.md
src/fhir/basic.ts
src/fhir/models/fhir-model.ts

This fixes two issues:
1. There could be permission issues around updating meta tags.
2. Meta tags are applied to all versions of the resource. Meaning if we were to archive and then unarchive, we'd lose the history of the archive action.

Use basic.code instead of meta.tag for archive/unarchive

---

.changeset/wise-moons-tickle.md
src/fhir/search-helpers.ts

Updating 3rd party tags to account for Quest and Collective.

CTW-648 3rd party tags

---

.changeset/wise-steaks-bake.md
src/fhir/medication.test.ts
src/fhir/medication.ts

Through our enrichment process we write a handful of RxNorm codes to medications - a code for the brand name, a code for the active ingredient, and the "SCD" code for the "Semantic Clinical Drug" which is the most granular way of how you can specify a medication - the chemical, the strength, the form. That's the code we want to use as _the_ RxNorm code for a med when we're adding it to the record, and this is especially important for the Canvas integration where they actually need to map the RxNorm to an FDB ID (the coding used as input in their system) and that specifically requires an SCD.
Because of some nuance in how SCDs are written to medications (see this Slack thread https://zushealth.slack.com/archives/C03DAL2K3NG/p1672950691733669) the best way for us to get these codes is by …

CTW-527 Updating logic for getting identifying RxNorm

---

.changeset/strong-turkeys-impress.md
src/components/content/medications/medication-actions.tsx
src/index.ts
src/utils/invalidate-queries.ts

These helper functions can be used internally or externally. The need came up to be able to invalidate medication query caches from code that uses the ctw-component-library. It is possible that a builder app knows a medication has been modified or stopped via some mechanism that isn't a component library component, and thus wishes to helpfully clear a cache.
Rather than have consumers of the library know about cache keys and which query library we use, they can just call a helper like `invalidateOtherProviderMedsQueries()` or `invalidateMedicationHistoryQueries()`.

Query Invalidation Helpers

---

.changeset/early-candles-design.md
src/components/content/condition-history/condition-history-filters.tsx
src/components/content/condition-history/conditions-history.tsx
src/fhir/conditions.ts

Do not fetch condition history for conditions with verification status of entered-in-error. Also do not remove entered-in-error from conditions with entered-in-error from the audit trail.

Remove entered in error audit trail

---

.changeset/ninety-experts-taste.md
src/fhir/medication.test.ts
src/fhir/medication.ts

Our logic to get the identifying RxNorm code on a medication statement should not have been preferring generics (ie. SCD RXCUIs). This has been causing an issue with duplicating resources via the reconciliation workflow in Canvas - when a user is presented with a branded drug (ie. an underlying SBD RXCUI) we are using the SCD to look up the medication in Canvas and thus creating a new unique lens resource after the reconciliation process.

CTW-686 Updating logic for getting the identifying RxNorm code on a medication

---

.eslintrc.cjs
package.json
src/components/content/CCDA/reactViewer.tsx
src/components/core/table/table-helpers.tsx

To avoid accidentally leaking the lodash `_` into the global scope we are disallowing imports directly from base packages "lodash" or "lodash/fp". Preferred usage would be to import and export lodash functions directly within the project modules "@/utils/nodash" and "@/utils/nodash/fp". See #413

CTW-706/Eslint rule to disallow lodash and lodash/fp imports

---

.changeset/famous-emus-draw.md
README.md
src/components/core/providers/ctw-context.tsx
src/components/core/providers/ctw-provider.tsx
src/utils/auth.ts

We now decode the access token to compute expiresAt. Also updated README and comments to encourage use of authTokenURL and not accessToken.

Simplify authTokenURL usage

---

.changeset/chilly-lies-obey.md
src/components/content/medications/medication-history.tsx
src/fhir/models/medication-statement.ts

Added patient managing organization to med statements in history. The majority of our med statements are produced either via CommonWell or Canvas. This will show the CommonWell org that we pulled the data from or "Firsthand" in the case of Canvas (though I need a follow-up task to ensure that managing org is set on firsthand patients, I'm not confident that's true).

CTW-737 Adding managing org to med statement in history

---

.changeset/healthy-gorillas-attack.md
src/App.tsx
src/components/content/conditions/patient-conditions-tabs.tsx
src/components/content/medications/other-provider-meds-table.tsx
src/components/core/badge.tsx
src/styles/tailwind.theme.ts

Added new color palette in our theming for "notifications" (discussed with Tai). Defaulting to the same colors as our primary color palette, but for Canvas we will be setting to red/white per their theming needs.

CTW-733 Notification badge styling

---

src/components/content/medications-table-base.tsx
src/components/content/medications/other-provider-meds-table.tsx
src/components/content/medications/patient-medications-tabbed.tsx
src/components/content/medications/patient-medications.scss
src/components/core/pagination/pagination-list.tsx
src/components/core/tab-group/tab-group.scss
src/components/core/tab-group/tab-group.tsx
src/components/core/table/table-rows.tsx
src/components/core/table/table.scss
src/components/core/table/table.tsx

This just moves the tabs from meds component into a reusable component.. no code change, just movement.
It also updated the empty state on the table.

TabGroup as reusable component and empty state for tables

---

.changeset/ten-jeans-relate.md
src/components/content/medications/other-provider-meds-table.stories.tsx
src/components/content/medications/other-provider-meds-table.tsx
src/components/content/medications/patient-medications-tabbed.stories.tsx
src/components/content/medications/patient-medications-tabbed.tsx
src/components/content/medications/patient-medications.stories.tsx
src/components/content/medications/patient-medications.tsx

The `OtherProviderMedsTable`, along with curated components `PatientMedications` and `PatientMedicationsTabbed` now accept an optional prop `hideAddToRecord`.

CTW-759 Add to Record can be hidden on medications table

---

.changeset/hot-needles-swim.md
src/components/content/medications/other-provider-meds-table.tsx
src/components/content/medications/patient-medications-tabbed.tsx
src/components/content/medications/story-helpers/mocks/other-provider-medications.ts
src/components/core/dropdown-action-menu.tsx
src/components/core/filter-bar/filter-bar-pills.tsx
src/components/core/filter-bar/filter-bar-pills/checkbox-pill.tsx
src/components/core/filter-bar/filter-bar-pills/select-pill.tsx
src/components/core/filter-bar/filter-bar-types.ts
src/components/core/filter-bar/filter-bar-utils.tsx
src/components/core/filter-bar/filter-bar.tsx
src/components/core/list-box/list-box.tsx

Some finishing touches/fixes on FilterBar
- "Clear all filters" is now "Remove all filters" and has an icon.
- Individual active filters have reset and remove actions with icons now. 
- Modified some types to support the above
- Improved some types on the FilterChangeEvent
- Added prescriber medication to filters

CTW-756 - Fix FilterBar types, language and edge cases

---

.changeset/grumpy-pumpkins-poke.md
package-lock.json
package.json

SideEffects set to prevent css from being tree-shaken by webpack.
Upgraded storybook to 7.0.0-beta.45

Fix/prevent tree shaking CSS

---

.changeset/funny-yaks-remember.md
src/components/content/conditions-table-base.tsx
src/components/content/conditions.tsx
src/components/content/conditions/conditions.stories.tsx
src/components/content/medications-table-base.tsx
src/components/content/patient-history/use-patient-history.tsx
src/components/core/table/table-helpers.tsx
test-runner-jest.config.js

https://www.loom.com/share/d15c858236ae42d48bd34d3c91eaad15
Added the ability to inform table columns that a sort index is a date. This way when the table sorts it can treat those indices appropriately. 
```tsx
{
title: "Some Date",
dataIndex: "someDate"
sortIndices: [
{ index: "someDate", isDate: true },
{ index: "somePerson", dir: "asc" },
],
},
```
Also fixed a small bug where the usePatientHistoryDetails react-query hook would error if the return value was empty.

CTW-758/Table sort indices supports `isDate`

---

.changeset/nervous-phones-shave.md
package-lock.json
src/components/content/medication-drawer.tsx
src/components/content/medications-table-base.tsx
src/components/content/medications/medication-history-drawer.tsx
src/components/content/medications/other-provider-meds-table.tsx
src/components/content/medications/patient-medications-tabbed.tsx
src/components/content/medications/patient-medications.tsx
src/components/content/medications/provider-inactive-medications-table.tsx
src/components/content/medications/provider-meds-table.tsx
src/components/core/drawer.tsx
src/components/core/providers/drawer-context.ts

In some EHRs we have this issue where opening a CTW drawer causes the entire chart to shift. We had previously gotten around this by adding logic to temporarily remove this `pushable` class from the chart just while the drawer is opening. Now that we've reduced our footprint by simply dropping in our `PatientMedicationsTabbed` component we no longer have the flexibility to add this kind of workaround when opening our drawer.
This PR exposes some props on the medications component that can be used to execute a function when opening the history drawer. 
Longer term we should find a way to more generally expose these kinds of functions to run upon opening a drawer because they are obviously not specific to medications.
https://user-images.githubusercontent.com/97455910/218780622-83e3853c-ab07 …

CTW-765 pushable issue

---

.changeset/little-parrots-add.md
src/components/core/error-boundary.tsx
src/components/core/tab-group/tab-group.tsx
src/utils/telemetry.ts

Ensured builder context is on both RUM and logging.
Improved page view names, for example:
- www.somebuilder.com/patient-portal
- ctw.zusapi.com/patients
We don't need to know if a person is on view named `/patients` or `/patient-portal`, instead we will tell RUM that view `PatientMedications` has loaded.
`TabGroup` component will now log when a tab changes.

Datadog - Improving view context

---

.changeset/popular-seahorses-give.md
src/components/content/conditions/patient-conditions.tsx
src/components/content/medications/patient-medications-tabbed.tsx
src/components/core/main.scss

[We had previously updated the default padding for components](https://github.com/zeus-health/ctw-component-library/commit/385304f13e14b0ae28d602195739abd12449b163#diff-85c539d3d5feacb483cc18d614e7de347974dc61eceae017276d8f7dc24412af). After some discussion we believe it makes more sense for consuming apps to determine the right amount of padding.

Removing default padding for components

---

.changeset/tender-cows-repair.md
.storybook/preview.jsx
src/components/content/allergies/patient-allergies.stories.tsx
src/components/content/allergies/patient-allergies.tsx
src/components/content/allergies/story-helpers/mocks/requests.ts
src/components/content/conditions/patient-conditions-actions.tsx
src/components/content/conditions/patient-conditions-tabs.tsx
src/components/content/conditions/patient-conditions.tsx
src/components/content/conditions/story-helpers/mocks/requests.ts
src/components/content/immunizations/patient-immunizations.stories.tsx
src/components/content/immunizations/story-helpers/mocks/requests.ts
src/components/content/medications-table-base.tsx
src/components/content/medications/patient-medications-tabbed.tsx
src/components/content/medications/patient-medications.tsx
src/components/content/medications/provider-meds-table.tsx
src/components/content/medications/story-helpers/mocks/requests.ts
src/components/core/main.scss
src/fhir/conditions.ts

As I started the ZusAggregatedProfile I realized storybook would need refactoring. That snowballed into a good place, but also lots of files touched. So this PR I removed the ZusAggregatedProfile component and left in storybook and component changes to support the mega component.
- MSW mocks now cleanup appropriately when changing to different components and reset completely before a new story begins.
- Medications and Conditions both mock `Basic` resource, which is fine, now it's double fine as both mocks can exist at same time (as they will need to in ZusAggregatedProfile story). Having multiple mocks for the same URL is fine, returning undefined from a handler allows other handlers to run. So the conditions mock of "Basic" now returns undefined if the resource sent in the request isn't …

Storybook Preperation for ZusAggregatedProfile

---

.changeset/eighty-radios-laugh.md
package-lock.json
src/components/content/timeline/patient-timeline-columns.tsx
src/components/content/timeline/patient-timeline.tsx
src/fhir/models/encounter.ts
src/fhir/system-urls.ts

CTW-741
CTW-740
* Added timeline table headers.
* Adjusted columns.
* Tweaked how encounter type is computed / what gets displayed.
* Bumped # of participants to display from 3 -> 6. This should handle the majority of cases. This was done to avoid the `+ # more` text, which will now appear above encounter location.

Timeline updates

---

.changeset/tender-grapes-rule.md
src/components/core/form/drawer-form.tsx

It is very hard to debug as a consumer of the drawerFormWithFields when it fails our validation as we can see the error or dont have access to the object. This just adds a log to help when debugging.

Add logging when form errors our validation

---

.changeset/large-geckos-smile.md
src/components/content/allergies/patient-allergies.tsx
src/components/content/conditions/patient-conditions.tsx
src/components/content/document/patient-documents.tsx
src/components/content/immunizations/patient-immunizations.tsx
src/components/content/medications-table-base.tsx
src/components/content/patients/patients-table.tsx

Wraps tables in `.ctw-overflow-hidden` because the -1px x margin on tables will cause a bold lefthand border if the table touches the sides of its container (and the container has a border). This happened even if the left and right borders of the table were off.
Telemetry and error boundary wrapper on Allergies, Immunizations and Documents.
Removed these two class names `ctw-items-center ctw-justify-between` from component containers (besides old meds and old conditions) as the classes don't affect the layout at all. Must have been a relic of when more content was in the body of components.
Removed the title bar from Documents and Immunizations as the V2 components don't need titles. It's becoming more of a CTW pattern than a CTW Component Library pattern.
Removed the padding on Patients …

Uniform tables and telemetry

---

.changeset/green-mails-walk.md
src/components/core/pagination/pagination.tsx

We no longer create a unique metric per page on "paginate" metrics.
Why: The `paginate_{number}` metric is now `paginate` because each unique metric here equals a handful of metrics which means `paginate_0` to `paginate_20` created ~100 custom metrics in our Datadog account.

CTW-681/fine scoped metrics for dashboard II

---

.changeset/itchy-cows-complain.md
src/components/content/allergies/patient-allergies-column.tsx
src/components/content/conditions/helpers/columns.tsx
src/components/content/conditions/helpers/patient-conditions.scss
src/components/content/document/patient-document-columns.tsx
src/components/content/immunizations/patient-immunizations-columns.tsx
src/components/content/medications-table-base.tsx
src/components/content/timeline/patient-timeline-columns.tsx

Fix alignment and size of status dots. Add underline on display when hovering on items in medication table.

Ctw 772/fix dot style

---

.changeset/flat-dots-end.md
src/components/content/condition-history/condition-history-filters.tsx
src/fhir/models/condition.ts

Couple of decisions that had to be made:
- We sort by hasEnrichment as well because we want enriched records to be preferred in uniqWith function.
- Sort by recordedDate and then version id because recorded date is can be a flat date and it was not sorting by the most recent record if it was on the same date. Not sure maybe instead of versionId maybe lastUpdated time from the meta tag?

Dedupe logic condition history

---

.changeset/rotten-ads-sip.md
src/fhir/search-helpers.ts

Re-add builder `_tag` to filters to fix issue with CPR records being duplicated.
Original pr: https://github.com/zeus-health/ctw-component-library/pull/542

Revert tag filter

---

.changeset/beige-pears-wash.md
src/components/content/condition-history/condition-history-schema.tsx

Display Zus status instead of clinical and verification status in history drawer preview
CTW-697

display zus status

---

.changeset/tame-foxes-unite.md
src/components/content/forms/schemas/validations.ts

This regex should allow for more phone number patterns, including a leading 1 and +# for country-code's.
Before:
After:

Switch to better phone number regex

---

.changeset/modern-ghosts-jump.md
src/components/core/filter-bar/filter-bar-pills/checkbox-pill.tsx
src/components/core/filter-bar/filter-bar.tsx
src/components/core/list-box/list-box.tsx

**NOTE TO REVIEWER: May want to view diff ignoring whitepsace.**
CTW Standalone -- Issue where "Add Filter" has bad padding due to CTW standalone resetting all button styles.
Now, our button uses `ctw-btn-clear` to get a cleaned up button and we tweak our spacing to add back the spacing the default padding was giving us. Also added vertical padding to increase click area.

Fix few style issues with filters

---

.changeset/smooth-stingrays-rest.md
src/components/content/conditions/helpers/filters.ts
src/components/content/conditions/helpers/patient-conditions-base.tsx
src/components/content/conditions/patient-conditions-outside.tsx
src/components/core/filter-bar/filter-bar-pills.tsx
src/components/core/filter-bar/filter-bar-pills/checkbox-pill.tsx
src/components/core/filter-bar/filter-bar-pills/select-pill.tsx
src/components/core/filter-bar/filter-bar.tsx
src/components/core/list-box/list-box.tsx
src/fhir/models/condition.ts
src/utils/filters.ts

Fixed up status filtering for conditions.
1. Show all status options independent of data.
2. Include "Unknown" in list of status options, with ability to filter unknown statuses.
3. Remove "Reset Filter" button from individual filters.
4. Apply filters that have 0 things checked. Luckily when you first add a filter, we don't applyFilters yet, giving users a chance to make some selections. This will also get reworked in the near future to default new checkbox filters to have an "All" selected.
Not implemented, just showing future "All" functionality.
New status filters (implemented here!)

CTW-667/condition unknown status

---

package-lock.json
src/components/content/zus-aggregated-profile/zus-aggregated-profile.stories.tsx

The issue was setupZusAggregatedProfileMocks is returning decorators but then we were overwriting it with our custom decorator. This caused a bug where on a fresh load certain resources would fail to fetch any data as the resource cache wasn't being initialized in the decorators as it should be.

Fix story decorators for scroll story

---

.changeset/grumpy-chicken-move.md
src/components/content/conditions/helpers/filters.ts
src/components/content/medications/helpers/filters.ts
src/components/content/resource/filters.ts
src/components/core/filter-bar/filter-bar-pills.tsx
src/components/core/filter-bar/filter-bar-types.ts
src/components/core/filter-bar/filter-bar.tsx
src/components/core/list-box/list-box.tsx

CTW-802
1. Get "Show Dismissed Records" showing up below the divider.
2. Get "Hide Dismissed Records" showing up when show is active.
Steps to get this working:
1. Simplified how divider is added, now `ListBox` can take a `{divider: true}` item and put a divider in that spot.
2. Renamed `belowTheFold` to `belowDivider` and added that to the newly refactored `dismissFilter`.
3. Added new `toggleDisplay` and `toggleIcon` options which will be displayed for active filters.
4. Changed `addOrRemoveFilter` to `toggleFilter` so now it knows whether this filter should be added or removed based on the current status.

CTW-802/show hide dismiss

---

.changeset/gorgeous-walls-scream.md
src/components/core/providers/drawer-provider.tsx

Fix bug where opening successive drawers outside of zap component causes apps to crash.

Ctw 903/open multiple drawers

---

.changeset/curly-balloons-travel.md
src/components/content/allergies/allergies-filter.tsx
src/components/content/allergies/helpers/sort.ts
src/fhir/models/allergies.ts

When deduplicating allergies and sorting allergies, we were using the display value as is, which unsurprisingly in healthcare is inconsistent. This change enforces lowercase on all operations that depend on case sensitivity like sort and filter

fix: allergies sort and dedupe are now done case insensitive

---

.changeset/gentle-sloths-rush.md
src/components/content/patient-history/use-builder-patient-history-list.ts

fix-patient-empty-messagesFix issue where when there are no messages results were still shown.

Fix issue where when there are no messages results were still shown.

---

.changeset/seven-pillows-draw.md
src/components/content/conditions/helpers/columns.tsx

Bolding conditions display per Canvas suggestion and UX approval.

CTW-782 making condition display value bold

---

.changeset/small-baboons-warn.md
src/components/content/patient-history/patient-history-table.tsx
src/components/content/patient-history/use-builder-patient-history-list.ts
src/fhir/models/patient-history.ts

Fixed date formatting and made the table default to sorting by patient history request initiated date descending. Have been using this page to review recent patient history requests and the lack of logical sorting was making it somewhat difficult. Please merge on approval.

Fixing date formatting and sorting for patient history requests

---

.changeset/tricky-tigers-impress.md
package-lock.json
package.json
src/components/content/forms/form-field.tsx
src/components/core/form/combobox-field.tsx
src/utils/telemetry.test.ts
src/utils/telemetry.ts

Removed RUM. The logging is still on (if telemetry enabled) and custom metrics are still sent through the proxy.
Additionally to lower noise, removed custom interaction metrics being sent each time someone focuses on an input field.

CTW-1021/Remove RUM

---

.changeset/giant-waves-destroy.md
src/App.tsx
src/components/core/providers/ctw-context.tsx
src/fhir/patient-helper.ts
src/fhir/search-helpers.ts

We removed the logic that filters by the users builder ID because we believed that the firstparty search parameter would take care of that for us. But that search parameter doesn't filter out all other builders data, it just filters out third party data. So because of CPR our query still returns data from other builders.

CTW-1069 Fixing queries that need to filter by users builder ID

---

package.json

Currently this library doesn't appear with a license on [NPM](https://www.npmjs.com/package/@zus-health/ctw-component-library) or in security scans.

Allow programatic detection of package license

---

.changeset/hip-kings-share.md
src/fhir/search-helpers.ts

As part of some recent performance tweaks we started doing more client-side filtering of data. For example, we are filtering by the builder tag to distinguish data owned by the user's builder. In a recent PR we added some logic to filter data returned by `searchBuilderRecords` to only data belonging to the current user's builder. This code set the `total` property of the response to the number of records returned, which broke any functionality that used `_count` and `_offset` for server side pagination because the returned result set never included a `total` representing all the data available, it just represented the data returned by that specific, paginated, request.
The short term fix here is to leave that `total` property untouched so it represents all the data available on the …

CTW-1079 Leave total returned by FHIR server

---

.changeset/itchy-tomatoes-teach.md
src/components/content/patient-history/helpers/filters.tsx
src/components/content/patient-history/patient-history-table.tsx
src/components/content/patient-history/use-builder-patient-history-list.ts
src/components/content/patient-history/use-patient-history.tsx
src/fhir/models/patient-history.ts
src/services/patient-history/patient-history-types.ts

CTW-1088
The patient history API returns data sorted by targetDate descending and has no sorting options. We display the createdAt field. This causes confusion as to why the table is ordered the way it is - for a customer that uses appointment-based patient history automation we are setting a target date based on upcoming appointments, so we're showing a bunch of unresolved/upcoming patient history requests on the first page, and they have very disparate create timestamps, so the data looks kind of nonsensical. We can alleviate this for the time being by displaying the target date for the "Last Queried" date and filtering the search to only return patient history requests that have a target date up until the current date (ie. don't show those that are set to happen in the future).

Fix sorting & display of patient history list

---

.changeset/thirty-guests-lick.md
src/fhir/binaries.ts

Failed look ups do not result in an error; rather, the response is a 403. Also, requests from ODS are base64 encoded and require decoding before returning the binary resource

fix: address issue where fallback to ods does not occur

---

.changeset/tricky-clouds-smile.md
src/components/content/conditions/patient-conditions-outside-badge.tsx
src/components/content/observations/patient-observations-outside-badge.tsx

Can't actually dismiss observations a.t.m but good to have the badge aligned with filtering out dismissed observations if/when we can dismiss them.

Ignore dismissed outside resources for badge count

---

.changeset/yellow-ravens-burn.md
src/components/content/medications/patient-medications-outside.tsx

I believe this particular bug was introduced when I refactored the “2.0” code for conditions and medications. The bug here is that clicking “dismiss” shows the loading spinner (good) but then stops showing spinner BEFORE the state is updated where we’d know this med is now archived. So the UI bug is: user click “dismiss” -> sees loading spinner -> stops loading but record still shows up as is treated as if it was not yet dismissed -> after a moment it then disappears (state update, med is now dismissed).
I added some debug message to useToggleArchive and to the med query itself. Here we can see that the top level code of useToggleArchive is getting called again and its isLoading is false . This happens after we trigger meds refresh, but BEFORE the meds get refetched. What’s suppose to …

Wait for meds refresh when dismissing meds

---

.changeset/hot-needles-talk.md
src/fhir/action-helper.ts
src/fhir/client.ts

FQS returns some non FHIR compliant data (nulls and reference resources). We now filter those out before saving to ODS.

Fix bug updating resources fetched from FQS

---

.changeset/nice-years-appear.md
src/fhir/models/document.ts

Currently we use the first attachment's creation date to define the document's "Date Created"; however, this is not guaranteed to be populated. This change leverages the Document Reference Date first, then fall back to the binary creation date if the document reference date is not present

fix: use document date first before using binary creation date

---

.changeset/clever-experts-switch.md
src/components/content/document/helpers/filters.test.ts
src/components/content/document/helpers/filters.ts

Currently the library can only render CCDA documents; hence, we filter out documents we cannot render to reduce confusion

fix: show only renderable binaries (at this time, only CW and CQ docs)

---

.changeset/wet-tips-study.md
src/components/content/medications/helpers/sorts.ts

Fixed a bug where the medications component was sorting dates in the wrong direction.

CTW-1224/medications date sorting direction

---

.changeset/serious-flowers-cross.md
package-lock.json
package.json

Pinning @radix-ui/react-dropdown-menu to patch version
> Using npm To Install A Specific Version Of A Node.js Package
npm allows you to use SemVer to specify the package version to install. You can use a caret (^) character to specify the latest minor version to install or a tilde (~) character to specify the latest patch version to install.

CTW-1208/radix-ui pin to patch version

---

.changeset/gentle-pugs-pay.md
src/components/core/providers/feature-flag-provider.tsx
src/hooks/use-feature-variant.ts

https://zeushealth.atlassian.net/browse/CDEV-52
This is another version of https://github.com/zeus-health/ctw-component-library/pull/836 w/ code simplification...
1. Simplified the `use-feature-variant` hook code 
2. `FeatureFlagProviderComponent` now only starts the unleash client once
3. Using a `FeatureFlagContext` to share state w/ `use-feature-variant` so that, when the unleash client errors, the hook [no longer has to wait for another error event to be emitted](https://github.com/zeus-health/ctw-component-library/pull/837/files#diff-3ef550bcba08c1508fe6c027cd24e131f59a90150b4f3025ccbc6c22af056d81L21-L25)
Tested:

CDEV-52: slowness v2

---

.changeset/six-laws-explain.md
package-lock.json
src/App.tsx
src/components/content/document/helpers/filters.ts

It is not guaranteed for a zus creation date to exist on a document reference; thus, we will default to not showing the document if the creation date is not present

fix: don't hard fail if creation date is missing, instead don't show the document

---

.changeset/metal-chairs-sit.md
src/App.tsx
src/components/content/allergies/patient-allergies.tsx
src/components/content/conditions/helpers/details.tsx
src/components/content/document/patient-document.stories.tsx
src/components/content/document/patient-documents.tsx
src/components/content/immunizations/patient-immunizations.tsx
src/components/content/resource/history.ts
src/fhir/allergies.ts
src/fhir/basic.ts
src/fhir/document.ts
src/fhir/immunizations.ts
src/fhir/medications.ts
src/hooks/use-medications.ts
src/services/conditions.ts

CDEV-224
* Switch allergies, conditions, documents, immunizations, & medications to use base variant and not *Drawer variant.
* Refactored a bunch of FQS | ODS queries to use new `useFeatureFlaggedQueryWithPatient` helper.
* Removed a few use-medication hooks that were no longer used.
* Changed `req.medication_history` metric to `req.timing.medication_history` to align with other metrics.

CDEV-224/Refactor FQS / ODS query code and remove "drawer" variants

---

.changeset/slimy-scissors-prove.md
src/services/fqs/queries/fragments/condition.ts

This PR adds managingOrganization to conditionHistory.

Add managingOrg to conditionHistory

---

.changeset/friendly-sheep-bow.md
src/components/content/resource/helpers/view-date-range.ts

CDEV-54
This way, medications that don't have a date, will still show up regardless of the date range view selection (e.g. "Past 6 Months" will return medications that have a date for that range AND any medications without a date).

Don't filter out resources without dates

---

.changeset/dry-balloons-sit.md
src/components/content/observations/helpers/details.tsx
src/components/content/resource/history.ts
src/components/content/resource/resource-details-drawer.tsx
src/fhir/provenance.ts

Setup provenance queries on-top of FQS. This is follow-up to https://github.com/zeus-health/ctw-component-library/pull/838.
* Enable provenance queries on FQS (feature-flagged)
* Use `provenances` variant feature flag for all provenance queries.

CDEV-215/FQS provenance

---

.changeset/real-bananas-own.md
src/services/fqs/queries/diagnostic-reports-query.ts
src/services/fqs/queries/fragments.ts

We now fetch all value types that a https://fhir-ru.github.io/observation.html can have.

Add all value types to observation fragment

---

.changeset/dirty-pugs-help.md
src/components/content/hooks/use-toggle-read.ts
src/components/core/providers/ctw-context.tsx
src/components/core/providers/use-ctw.ts
src/utils/auth.ts

Checking the environment and user type when marking a record as read, if we're in production and it's a non-builder user then don't allow it. We could add this protection to dismissal but this feels a bit hack and it's really to protect against Zus users marking records as read because they simply clicked on them.

CTW-1240 Preventing non-builder users from marking records as read in production

---

.changeset/grumpy-weeks-flash.md
src/fhir/allergies.ts
src/fhir/care-team.ts
src/fhir/diagnostic-report.ts
src/fhir/document.ts
src/fhir/encounters.ts
src/fhir/immunizations.ts
src/fhir/medications.ts
src/services/conditions.ts
src/services/fqs/client.ts

Fixes both https://zeushealth.atlassian.net/browse/CDEV-246 and https://zeushealth.atlassian.net/browse/CDEV-247
FQS can return both `errors` and `data` for a single request. 
This PR allows us to still use `data`, if it exists, even if there are `errors`.
i got all the requests except these which are a bit different:
* https://github.com/zeus-health/ctw-component-library/blob/29b24fe333ed1c375f33e6dcdbb5f03f2c096f9f/src/components/content/resource/history.ts#L196
* https://github.com/zeus-health/ctw-component-library/blob/29b24fe333ed1c375f33e6dcdbb5f03f2c096f9f/src/components/content/resource/history.ts#L223
* https://github.com/zeus-health/ctw-component-library/blob/29b24fe333ed1c375f33e6dcdbb5f03f2c096f9f/src/services/fqs/long-poll-fqs.ts#L40
* …

ignore FQS graphql errors when there is also data returned

---

.changeset/smart-ties-lie.md
src/App.tsx
src/components/content/zus-aggregated-profile/zus-aggregated-profile-tabs.tsx

Right now the notification icon doesn't always display to the left, and vertically aligned, with the tab title.
We do still have an issue with the tab title content shifting when the notification icon goes away (ie. you've read the last resource). We could address this by having the icon always there and adjusting the opacity, but that looks pretty awkward with the icon on the left. Perhaps if/when we move the icon to the right we can take this approach.

fixing styling of notification icons

---

.changeset/happy-berries-return.md
package-lock.json
src/App.tsx
src/fhir/medications.ts

The outside medications history requests were not using a specific enough caching key and so the cache entry was being shared across all meds for a given patient. This PR adds the medication ID to the cache key so that each medication history has a separate cache entry.

Fix: outside meds history caching

---

.changeset/breezy-parrots-heal.md
src/fhir/medications.ts

https://zeushealth.atlassian.net/browse/CDEV-257
A discrepancy that was noticed in the attached JIRA ticket surfaced an issue where the med history deduping logic just grabs the first med history in the result set. This results in discrepancies between which med history gets displayed in the UI when the data from ODS comes in a different order than the data from FQS.
This ticket forces the results to be sorted by resource ID, which ensures that- regardless of the data source- the data displayed should be the same.

CDEV-257: Force med results to be sorted by resource ID

---

.changeset/odd-crabs-grin.md
src/components/content/zus-aggregated-profile/zus-aggregated-profile-tabs.tsx
src/components/core/tab-group/tab-group.tsx

This `ctw-pt-5` class is adding padding to the top of some of the tabs in the ZAP and it does not appear necessary anymore. See video below for the discrepancy between conditions (where it looks good) and allergies (where it currently looks bad).
https://github.com/zeus-health/ctw-component-library/assets/97455910/0b75b3d7-ad1d-4672-9b8e-e66d6f6796a0

Removing padding from top of allergies/documents/immunizations/timelines

---

.changeset/lucky-bulldogs-lay.md
src/components/content/allergies/unread-allergies-notification.tsx
src/components/content/conditions/patient-conditions-outside-badge.tsx
src/components/content/immunizations/unread-immunizations-notification.tsx
src/components/content/medications/patient-medications-outside-badge.tsx
src/components/core/unread-notification-icon.tsx
src/components/core/unread-notification.tsx

Always nice when you can delete more code than you add... (by one line :p). 
Exposing `className` prop in the allergies/immz unread notifications and making the logic for the unread notification components more generic.

CTW-1282 Further refactoring of unread notifications

---

.changeset/forty-files-talk.md
src/components/content/document/helpers/columns.tsx
src/components/content/document/helpers/sorts.ts
src/components/content/document/patient-documents.tsx
src/components/content/medications/patient-medications-outside.tsx
src/components/content/resource/helpers/view-date-range.ts
src/components/content/timeline/patient-timeline.tsx
src/fhir/models/document.ts
src/services/fqs/queries/documents.ts

CDEV-40
Revamp documents component:
* Add encounter date which is based on `document.context.period`.
* Re-ordered columns
* Default view is now "All Time"
* Added sort and set default to New to Old (based on `encounterDate || dateCreated`)
* Changes to details drawer:
* Removed date from title and added encounter date as sub header.
* Removed `status` and `docStatus`
* Section display now separates items with bullet points.
* Added date retrieved (dateCreated)
[Figma documentation](https://www.figma.com/file/c3tY2coG2tYOoWSVwoBKCN/Document-Viewer-V1?type=design&node-id=547-6720&mode=design&t=gZsSOG2u3kbR6k5d-0)

Revamp documents component (add sort, encounter date, cleanup details)

---

.changeset/eleven-queens-build.md
src/components/content/resource/resource-table.scss

Unread/dismissed styles are being overridden in a consumer app. Increasing the specificity of the selectors to address this so that the styles win out.

Increasing specificity of CSS selectors for unread/dismissed

---

.changeset/sour-shrimps-arrive.md
src/components/content/conditions/helpers/history.tsx
src/fhir/codeable-concept.ts
src/fhir/models/condition.ts

CDEV-9
Finds the first text or display from the categories, otherwise we don't show category. So if the only categories that exist only have codes, we'll just not show category at all.
The following `category` would result in `Diagnosis`.
```js
[
{
coding: [
{
system: "http://snomed.info/sct",
code: "282291009",
},
],
},
{
coding: [
{
system: "http://snomed.info/sct",
code: "282291009",
},
{
system: "http://loinc.org",
code: "29308-4",
display: "Diagnosis",
},
{
display: "Foobar",
},
],
},
];
```

Improve surfacing category text/display

---

.changeset/young-snails-glow.md
src/components/content/observations/helpers/columns.tsx
src/components/content/observations/helpers/details.tsx
src/services/fqs/queries/observations.ts

https://zeushealth.atlassian.net/browse/CDEV-293
Resolved issue where observation trends were displaying the same value: this was due to the UI being incorrectly wired to pull from the clicked-Observation value vs the trend value.
Additionally:
1. Fixed sorting issue where trends weren't always being chronologically sorted
2. Updated some styling to better display result values
3. Added missing `interpretation` fields to graphql query that are responsible for showing interpretation text in the UI

CDEV-293: Resolving issue w/ repeated observation values

---

.changeset/nice-humans-collect.md
src/components/content/observations/helpers/columns.tsx
src/fhir/observations.ts

https://zeushealth.atlassian.net/browse/CDEV-290
Removed first-party filter from FQS request when fetching observations, and cleaned up corresponding telemetry. Adding click telemetry to Trends.

CDEV-290: Cleaning up observation requests and telemetry

---

.changeset/sixty-trees-hang.md
src/fhir/models/condition.ts

Minor fix so we display unknown condition types with the string "Unknown".

Fix to display of unknown condition type

---

.changeset/strange-bobcats-agree.md
src/components/content/zus-aggregated-profile/zus-aggregated-profile-tabs.tsx
src/components/core/list-box/list-box.tsx
src/components/core/tab-group/tab-group.scss
src/components/core/tab-group/tab-group.tsx

CDEV-278
CDEV-273
Features:
* Takes into account any topRightContent like "Request Records"
* Reserves space for the "More" menu unless we're calculating the space for the last tab as we'd then hide the more menu.
* Only show more menu when breakpoints.sm and when doing so, show the tab name instead of "More".
Additionally:
* Setup ListBox to optionally take a `ref` (used to determine size of more button)
* Added optional `selectedIndex` to ListBox so that we can control the selected item from the outside.
* Tweaked unread notification bullet to be absolutely positioned within ZAP tabs and more menu. This prevents content shifting when notification comes in or out.

Improve responsiveness of ZAP tabs

---

.changeset/eighty-pants-brake.md
src/App.tsx
src/components/content/unread-records-notification.tsx
src/components/content/zus-aggregated-profile/zus-aggregated-profile.tsx

Sets up the ZAP so that you don't _need_ to pass in the resources and we have a default set. Will follow this up with a corresponding update in standalone.

Setting up default resources for the ZAP

---

.changeset/empty-zebras-draw.md
src/components/content/observations/helpers/drawer.tsx
src/components/core/providers/patient-provider.tsx
src/fhir/observations.ts

https://zeushealth.atlassian.net/browse/CDEV-296
The FQS "filter Observations by LOINC code" feature is now available, but unfortunately only net-new Observations will be returned until a backfill of all historical data is complete. This means that we could possibly return incomplete trend data if a Patient has historical Observations **and** net-new Observations.
To guard against returning incomplete trend data, this PR checks when the Patient was created and will only fetch Observations when the Patient was created after the 7/19/2023 date (which is when FQS first introduced the filter feature). 
This means we will only show trend data on recently created Patients. Once the FQS backfill of Observation data is complete, we can remove this restriction and show trend data for all Patients.

CDEV-296: Only fetch trend data if Patient is new

---

.changeset/metal-paws-buy.md
src/components/content/conditions/helpers/modal-hooks.tsx
src/components/content/medications/helpers/add-new-med-drawer.tsx
src/components/content/observations/helpers/drawer.tsx
src/components/content/patient-history/use-patient-history.tsx
src/components/content/resource/resource-details-drawer.tsx
src/components/core/providers/drawer-context.ts
src/components/core/providers/drawer-provider.tsx
src/components/core/view-fhir.tsx
src/utils/session.ts
src/utils/telemetry.ts

Send a metric for active session and for opening a drawer.
When an interaction is made (currently just opening a drawer) we track a session in localStorage. A new session doesn't begin until an hour after no other interaction is made by the same user. We send a `ctw.active_session` metric count to DataDog.
This doesn't cover the whole of CTW-1114, it doesn't do any tracking in DynamoDB so we can't yet track user retention, only user activity totals. I want to get this merged a bit early to allow others to work on some interaction metrics and while I spike on the best way to complete the rest of CTW-1114 ticket in a way that supports better long term outcomes.

CTW-1114/Track active session and generic drawer open

---

.changeset/fresh-apricots-ring.md
src/fhir/observations.ts

https://zeushealth.atlassian.net/browse/CDEV-296
Only fetch trend data for patients created on or after 07/19/2023 (previously 07/20/2023)

CDEV-296: Updating trend fetching to include patients created on 07/19

---

.changeset/eleven-cycles-exist.md
package-lock.json
src/utils/telemetry.test.ts
src/utils/telemetry.ts

https://zeushealth.atlassian.net/browse/CDEV-290
Adding a `user_id` tag to our existing metrics that get collected for easier reporting on unique users per action

CDEV-290: Adding user ID tag to metrics

---

.changeset/tidy-meals-explain.md
src/components/content/conditions/patient-conditions-all.tsx
src/components/content/medications/patient-medications-all.tsx

This fixes a bug where an already read record could get marked as unread when hitting the "Add" row action.

Only toggle read on add if not already read

---

.changeset/beige-berries-sort.md
src/components/content/allergies/patient-allergies.tsx
src/components/content/care-team/patient-careteam.tsx
src/components/content/conditions/helpers/details.tsx
src/components/content/conditions/helpers/patient-conditions-base.tsx
src/components/content/conditions/patient-conditions-all.tsx
src/components/content/conditions/patient-conditions-outside.tsx
src/components/content/conditions/patient-conditions.tsx
src/components/content/document/patient-documents.tsx
src/components/content/hooks/use-toggle-dismiss.ts
src/components/content/hooks/use-toggle-read.ts
src/components/content/immunizations/patient-immunizations.tsx
src/components/content/medications/helpers/details.tsx
src/components/content/medications/helpers/patient-medications-base.tsx
src/components/content/medications/patient-medications-all.tsx
src/components/content/medications/patient-medications-outside.tsx
src/components/content/observations/helpers/drawer.tsx
src/components/content/resource/resource-details-drawer.tsx
src/components/content/resource/resource-table.tsx
src/components/content/resource/use-additional-resource-actions.tsx
src/components/content/timeline/helpers/modal-hooks.tsx
src/components/core/drawer.scss
src/components/core/drawer.tsx
src/components/core/table/table-rows.tsx
src/components/core/table/table.tsx
src/fhir/basic.ts
src/fhir/models/fhir-model.ts

Reworked row actions and plumbed them to the details drawer. This way details drawer will always show the same actions as shown on row hover.
Additionally:
* Reworked row actions to optionally take an `onSuccess` prop so that we can close the drawer for certain actions (dismiss/mark as new/remove).
* Refactored the addition of dismiss & read actions into `useAdditionalResourceActions` so that it can be used by both the `ResourceTable` and `ResourceDetailsDrawer`.
* Reworked dismiss/restore and read/new to update the model record optimistically. This fixes a bug where the row action button on hover would briefly show the old state after the spinner was done. It also allows us to mark a record as read and not wait before opening the drawer. The drawer will then correctly render a "mark as …

CDEV-70/details drawer actions

---

.changeset/hot-doors-approve.md
src/components/content/diagnostic-reports/helpers/columns.tsx
src/components/content/resource/helpers/resource-title-column.tsx
src/fhir/models/allergies.ts
src/fhir/models/condition.ts
src/fhir/models/document.ts

Our default behavior was to capitalize the resource table title but that's really a very case-by-case decision. Labs/immz/meds all have strings that don't make sense when you generically apply the lodash capitalize function. So this PR removes that behavior from the title component and leaves it up to the model getter to decide how to capitalize.

Fix capitalization for resource table title/description column

---

.changeset/six-buttons-yawn.md
src/fhir/models/diagnostic-report.ts
src/fhir/resource-helper.ts
src/services/fqs/queries/diagnostic-reports-query.ts

https://zeushealth.atlassian.net/browse/CDEV-350
The Diagnostics Report Drawer was erroring out when loading Diagnostic Reports that had contained Observations. This PR:
1. Updates the Diagnostics Report FQS query to include all fields required by the Diagnostics Report Drawer
2. Updates the Diagnostics Report model to **additionally** populate Observations from contained Observations
3. **Updates the `findReference` resource helper to support finding contained resources in GraphQL responses, as previously it would not properly traverse these nodes... GraphQL contained resources are nested another level deep when compared to the previous ODS contained resource responses**

CDEV-350: Adding support for contained resources to Diagnostics Report Drawer

---

.changeset/seven-points-cough.md
src/components/core/tab-group/tab-group.tsx

CDEV-358
We want to avoid drop down menus for tab groups getting cut off on the right, by making them right-aligned when necessary.
The class `ctw-right-0` is added to right-align the dropdown except in the following conditions:
- If the drop down is not on the rightside edge because of a non-tab element, it looks better left-aligned
- If the drop down is on the left side, we want it to be left-aligned

CDEV-358 Self-adjusting alignment of dropdown for tab groups

---

.changeset/spicy-dingos-mix.md
src/components/content/observations/helpers/trends.tsx

This PR adds the capability to track when a trend has been clicked.

CDEV-356/Add telemetry to track clicking trends

---

.changeset/chatty-parrots-clap.md
.changeset/poor-paws-fry.md
package-lock.json
src/components/content/document/helpers/filters.test.ts
src/components/content/document/helpers/filters.ts
src/components/content/resource/helpers/filters.ts
src/components/content/resource/resource-details-drawer.tsx
src/fhir/binaries.ts
src/services/fqs/queries/provenances.ts

CDEV-292
Updated fix without the bug that removed the "Source Document" button for all resources caused by the "instanceof DocumentModel" condition.
Follows Bryan's solution, which can be found in the ticket comments

Cdev 292 dont show unrenderable source documents

---

.changeset/big-falcons-change.md
package-lock.json
src/components/content/conditions/patient-conditions-all.tsx

CDEV-368
Previously I removed the default filter in the base Conditions table, a component used by some of the displayed Conditions tables but not `conditions-all`. This PR removes it from `conditions-all`.

Remove default filter for conditions-all table + changeset

---

.changeset/strong-beers-sneeze.md
src/index.ts

Currently the red dot is missing from CTW's side tab for Encounters & Notes. This exports the component, allowing it to be used in the standalone app.

Allow Unread Encounters Notification Icon to Appear Outside of Components

---

.changeset/purple-emus-relax.md
src/App.tsx
src/components/content/zus-aggregated-profile/zus-aggregated-profile-iframe.tsx
src/components/core/providers/theme/context.ts
src/components/core/providers/theme/theme-provider.tsx

The theme passed to the CTWProvider now allows for an optional `iframe` attribute which includes theming that can't be accomplished via tailwind as it is currently. The `iframe` theme has 3 optional properties fontFamily, fontSize and lineHeight which can be used to make the iframe embedded ZAP look more like the rest of the webapp.

CTW-1348/Embedded ZAP custom fonts

---

.changeset/curly-tomatoes-rest.md
package-lock.json
src/components/content/encounters/helpers/filters.test.ts
src/components/content/encounters/helpers/filters.tsx
src/fhir/encounters.ts
src/fhir/models/encounter.ts

CDEV-318
Summary of my code:
- Dedupes encounters by certain fields, which are required for deduping. Merges the dupes into one encounter with as many and as recent fields as possible from each dupe.
- Use the deduping/merging every time encounters are fetched.
- Unit tests

Cdev 318 deduplicate encounters in encounters notes component

---

.changeset/yellow-plums-brush.md
src/components/content/CCDA/ccda_viewer/components/Section/Section.tsx

Replace dangerously setting inner html with Interweave instead, for CCDA docs.

Replace dangerously set inner html (part 2)

---

.changeset/honest-bags-beam.md
src/components/content/patient-record-search/helpers/result-type/result-allergy-intolerance.tsx
src/components/content/patient-record-search/helpers/result-type/result-condition.tsx
src/components/content/patient-record-search/helpers/result-type/result-document.tsx
src/components/content/patient-record-search/helpers/result-type/result-med-statement.tsx
src/components/content/patient-record-search/helpers/result-type/result-observation.tsx
src/components/content/patient-record-search/helpers/style.scss
src/components/content/patient-record-search/patient-record-search.tsx

Fixed CSS styles on heading and spacing between results as those styles were not applied in ctw.
In CTW the heading and spacing didn't come across:
Made those explicit in the PR:

CTW-1240/Search Tool Smal CSS Fix

---

.changeset/young-trains-pretend.md
src/components/content/patient-record-search/helpers/result-type/result-med-statement.tsx
src/components/content/patient-record-search/helpers/style.scss

- Remove padding from medication row
- CTW resets the browser h3 margin-block-start to 0. To normalize it this PR sets it to `1rem` (just for this component). There is no tailwind equivalent that I could find which is why I used css and not a tailwind class.

CTW-1366/Fix width of medication row

---

.changeset/silly-frogs-return.md
src/App.tsx
src/components/content/medications/patient-medications-all.tsx
src/components/content/medications/patient-medications-outside.tsx
src/components/content/zus-aggregated-profile/zus-aggregated-profile-iframe.tsx

- Handle callbacks for `onAddToRecord` handlers when medications are added within the embedded iframe ZAP.
- Typing for the ZAP MessageEvents
---
Because we're continuing to add more event types with different use cases and bodies, this PR also adds some typing to the messages being sent from parent and iframe. The TLDR is that in there is now a `payload` and `error` attribute on the message data:
```ts
data: {
type: string.   // this is unchanged from how we did it before
payload: T      // this is new, instead of adding attributes to the flat `data` object. A successful
//  event can post a message with attributes on the `data.payload` object.
error?: string  // An unsuccessful event can post an error message.
```
This isn't just stylistic, the reason here is to separate transport …

CTW-1370/iframe ZAP onRecordSave for medications

---

.changeset/heavy-walls-cough.md
src/components/core/icons/zus-icon.tsx

When "zus" text isn't shown in `ZusIcon`, the viewport will dynamically adjust.

ZusIcon viewport dynamically changes based on content

---

.changeset/twenty-points-prove.md
src/components/content/encounters/helpers/modal-hooks.tsx
src/utils/dates.test.ts
src/utils/dates.ts

If an encounter has both a start and end date that are the same, we used to render it as `01/01/2022 - 01/01/2022`. With this PR, it will now only show `01/01/2022`

fix: only show one date if both dates are the same

---

src/components/content/patient-record-search/helpers/relevant-content.tsx
src/components/content/patient-record-search/helpers/search-result-row.tsx

The function `getNonOverlappingSpans` I pulled from chatGPT in the off-chance that we end up with overlapping spans we can merge them into an array on non-overlapping spans. If it's not possible that spans overlap though, we could remove this function and just keep `getRelevantContentFromDocumentSearchResult`.
Also, I didn't test this out on search results

Highlight spans in relevant content

---

.changeset/curvy-tomatoes-travel.md
src/components/content/encounters/helpers/columns.tsx
src/components/content/resource/helpers/details-card.test.tsx
src/components/content/resource/helpers/details-card.tsx

If a discharge disposition exists for an encounter, we'll add it as the first item in the `Details` column

fix: add discharge disposition to details cell

---

.changeset/six-ligers-joke.md
src/components/content/resource/helpers/details-card.test.tsx
src/components/content/resource/helpers/details-card.tsx
src/components/content/resource/helpers/note-style.scss

Addresses a few issues with clinical notes:
1. Verify the table actually has a `thead` and `tbody` before trying to transpose
2. Show loading status while transposing table
3. Switch from `<table>` to `<div>` for transposed rows. This results in a cleaner experience

fix: address clinical note issues

---

.changeset/shaggy-crabs-press.md
src/components/content/allergies/helpers/history.tsx
src/components/content/resource/history.ts
src/services/fqs/queries/conditions.ts
src/services/fqs/queries/fragments/condition.ts
src/services/fqs/queries/versions.ts

See [this slack thread](https://zushealth.slack.com/archives/C03NWTVCGJV/p1695221829563379) for background on discussion with product/UX.
Essentially we have deemed that it is unnecessary to surface the version history *of a single FHIR resource* in the history section of the details drawer. The primary intent of this section is to highlight what other organizations have participated in care, so being able to show something like the status transitions of a condition (eg. when it went from active to inactive) is not necessary. In an effort to simplify the code and the logic behind this feature, reduce calls to the back-end, and address the bug in CTW-1398 where we're showing "Unknown" as the title for older versions of a condition resource, we are removing this functionality.

CTW-1398 Remove version history from resource history drawer

---

.changeset/nine-chefs-repair.md
src/components/content/allergies/helpers/column.tsx
src/components/content/allergies/helpers/history.tsx
src/components/content/allergies/patient-allergies.tsx
src/fhir/models/allergies.ts
src/fhir/models/condition.ts
src/fhir/models/fhir-model.ts
src/fhir/models/patient.ts

Some 3rd party networks contribute data to patients with no managing organization. This results in "Unknown" showing up in the app. We should use the phrase "Sourced from EHR Networks". Discussed w/ UX.

CTW-1398 Show "Sourced from EHR Network" instead of "Unknown" for 3rd party data without a managing org

---

.changeset/violet-oranges-applaud.md
src/components/content/patient-record-search/patient-record-search.tsx
src/components/content/zus-aggregated-profile/zus-aggregated-profile.tsx
src/fhir/document.ts
src/services/fqs/queries/documents.ts
src/services/patient-record-search/patient-record-search.ts

Updating search so that we include the semantic search if the search phrase has more than 2 words. If the user ends with a question mark we'll also include the AI generated response. This behavior is subject to change in the future, just doing this as a short term way of making it available in the app.
Also fixing an issue with how we retrieve documents from FQS by ID.

CTW-1388 Enable semantic and generative search results

---

.changeset/clever-plums-fly.md
src/components/core/list-box/list-box.tsx

Change "Add Filter" dropdown whitespace to not break lines
and instead to stay on the same line

Fix add filter button text whitespace breaking

---

.changeset/silver-baboons-nail.md
src/components/content/patient-history/use-patient-history.tsx

This updates calls to patient-history to use `patient-history.zusapi.com` and its respective other environmental endpoints.

Update patient-history URL

---

.changeset/gorgeous-tomatoes-sell.md
src/components/content/zus-aggregated-profile/zus-aggregated-profile-iframe.tsx

IFrame ZAP should have the same ThemeProvider context as the parent window ThemeProvider. The `theme` passed into `CTWProvider` contains both the tailwind theme and iframe theme. The `ZusAggregatedProfileIFrame` component gets those two themes from the `ThemeProvider` as separate objects. Originally we would send the iframe theme as a separate configuration to the standalone ZAP, but then in the standalone ZAP the `ThemeProvider` actually doesn't have the iframe theme. The `Drawer` component now uses the `ThemeProvider` to access the iframe theme as well so we need to make sure it's in the `CTWProviderProps["theme"]` sent to the iframe.

IFrame ZAP to pass same theme to CTWProvider as parent window.

---

.changeset/wet-cheetahs-prove.md
src/components/content/patients-adt/patients-adt-alerts-table.tsx
src/components/content/resource/helpers/view-date-range.ts

CDEV-471
Changes the views for the ADT table to inclue past 7 days and instead of all time, 90 days

CDEV-471 ADT Table: Add 7days, remove all time

---

.changeset/clean-dryers-tell.md
src/components/content/encounters/helpers/modal-hooks.tsx
src/components/content/overview/patient-subscription.test.ts
src/components/content/overview/patient-subscription.tsx

Modifying the subscription description to exclude references to specific time intervals (per DA's direction), making the description text smaller, and ordering notes in encounter drawer alphabetically to be consistent with document drawer.

CTW-1445 Modify subscription description

---

.changeset/twelve-islands-share.md
src/components/content/overview/patient-overview.tsx
src/index.ts

Care team users don't currently have the necessary permissions to view package metadata, so they get a 401 when we try to display patient subscriptions. Temporarily removing this functionality until we get the permissions sorted out. Also exporting the overview component and the subscription description component so we can use them in standalone.

CTW-1445 Hiding subscription info until we get permissions sorted out

---

.changeset/yellow-doors-drum.md
src/components/content/resource/helpers/view-button.tsx
src/components/content/resource/resource-table-actions.tsx
src/components/core/drawer.tsx
src/components/core/filter-bar/filter-bar.tsx
src/components/core/sort-button/sort-button.tsx

When the resource action buttons (view, sort and filter) were on small screens they went full width. This PR makes it so their edges align with the other content of the ZAP.
Additionally on iframe the "Close" button on drawer now says, "Back" to match the close button icon switch from ❌ to ◀️ .

Add padding to sides of resource action buttons on xs viewport

---

.changeset/thirty-turtles-smell.md
.eslintrc.cjs
package-lock.json
package.json
src/components/core/providers/patient-provider.tsx
src/components/core/providers/use-query-with-ctw.ts

Add recommended `@tanstack/query` plugin to help ensure we keep up with best react query linting rules. Tested locally with a few patients to ensure queries looked like they were behaving the same.

add lint rules around react query

---

.changeset/spicy-falcons-suffer.md
package-lock.json
src/components/content/zus-aggregated-profile/zus-aggregated-profile-iframe.tsx
src/components/core/error-boundary.tsx

Approach taken from -- https://github.com/bvaughn/react-error-boundary/blob/master/src/withErrorBoundary.ts#L13
See discussion -- https://zushealth.slack.com/archives/C05231F29LP/p1696952204445749
tl;dr: This should fix an issue in CTW standalone where components that throw errors were not properly being caught by `withErrorBoundary`. This was due to the fact that we were doing `wrappedComponent(props)` which meant the wrapped component was rendering **outside** the `ErrorBoundary` component. This prevented `ErrorBoundary` component from catching the error.

Fix withErrorBoundary to better capture errors

---

.changeset/eighty-bobcats-yell.md
src/fhir/observations.ts

DRT finished back-filling data so that we no longer need this date check on patient observations.

CTW-1512 Removing date check on observations now that back-fill is done

---

.changeset/clever-gorillas-pull.md
src/services/subscriptions/subscriptions.ts

I had originally tested the UI against a sandbox test patient that didn't have a subscription package and I had tested the network calls manually against Postman. Clearly not sufficient testing. I tested this PR by running the component library against a patient with an actual subscription package and verified that the subscription info is rendered correctly. I will verify in prod after deploy by going to a patient with a package subscription and confirming the subscription info is rendered correctly.

CTW-1530 fixing issue with package response type

---

.changeset/strange-rabbits-compete.md
src/components/content/patient-history/patient-history-action.tsx
src/components/content/zus-aggregated-profile/zus-aggregated-profile.tsx
src/components/core/providers/ctw-context.tsx
src/hooks/use-feature-toggle.ts

Support feature flag ctw-patient-history-form. This will hide the request records button if this flag is disabled. It is enabled for everyone currently.
Tested this running locally by toggling the `ctw-patient-history-form` feature flag in unleash to be disabled for that builder.

CTW-1497/Support feature flag ctw-patient-history-form

---

.changeset/perfect-experts-double.md
src/components/content/patients-adt/patients-adt-alerts-table.tsx

[CTW-1532](https://zeushealth.atlassian.net/browse/CTW-1532)
Remove 3 month view from the Hospitalizations table, as part of setting 30 days as the new maximum history.
[CTW-1532]: https://zeushealth.atlassian.net/browse/CTW-1532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CTW-1532/ADT Remove 3 months

---

.changeset/pretty-impalas-cover.md
src/services/fqs/queries/fragments/condition.ts

Jira Ticket Number: CTW-1519
Continuation.
Fixes bug introduced by previous PR related to this ticket, which caused the conditions query to fail.
Issue was that the patients fragment was called but not the organization fragment.  
Manually. Query no longer errors:
Manually checking.
_NOTE:_ This template comes from [here](https://github.com/zeus-health/.github/blob/main/PULL_REQUEST_TEMPLATE.md).
If you would like to suggest modifications to this template, open a PR.

CTW-1519/Fix condition request

---

.changeset/rare-suns-travel.md
src/components/content/medications/patient-medications-all.tsx

Jira Ticket Number: CTW-1577
We have been showing the "Add" button in the medication drawer even when `readOnly` is set to true. This PR fixes that issue.
Tested locally with `readOnly` set both ways.
I will verify in Elation sandbox that it is set up as expected.
Need to do CTW version bump.

CTW-1577 Fixing issue with showing add button when we shouldn't

---

.changeset/flat-spoons-vanish.md
package-lock.json
src/fhir/codeable-concept.test.ts
src/fhir/codeable-concept.ts
src/fhir/models/medication-statement.ts

Jira Ticket Number: CTW-1526
Improves how we find the appropriate "label" for a codeable concept. We can now optionally specify a system to favor, in which case we'll try and find the `display` value associated with that system coding (skipping those with extensions so that we skip enrichments). Additionally, instead of falling back to the first coding when there is no text, we now instead fall back to the first coding with a display, and then first coding with a code.
Wrote unit tests and verified data in component for my sandbox builder.
Verify in sandbox/prod and check with team.

Favor showing RxNorm display values for medication

---

.changeset/soft-toys-sniff.md
src/components/core/filter-bar/filter-bar.tsx

Jira Ticket Number: none
The issue is that the CSS for FontAwesome comes in async so the default inline style on the icon isn't present on page load. This causes the + icon and the "Add Filter" text to wrap to two lines in CTW briefly.
Manually tested same change in CTW.
Deploy to remix/next and verify it is no longer flashing wrapped.

Minor hack to fix + and "Add filter" wrapping

---

.changeset/loud-days-reply.md
patches/fhir-kit-client+1.9.2.patch

Jira Ticket Number: CTW-1558
Drops cross-fetch/polyfill usage from our fhir-kit-client dependency.
Manually tested resulting `dist` folder in component library build within the node_modules of https://github.com/luthfib/auth0-nextjs-repro/tree/fetch-issue and saw problem go away.
Upgrade component library version in the `auth0-nextjs-repro` and verify problem is now fixed. Then do the same for the CTW next app.

Drop cross-fetch/polyfill from fhir-kit-client

---

.changeset/cool-stingrays-reflect.md
src/components/content/conditions/patient-conditions-outside.tsx
src/components/content/hooks/use-toggle-dismiss.ts
src/components/content/hooks/use-toggle-read.ts
src/components/content/medications/patient-medications-all.tsx
src/components/content/medications/patient-medications-outside.tsx
src/components/content/resource/resource-table.tsx
src/components/content/resource/use-additional-resource-actions.tsx
src/fhir/action-helper.ts

Jira Ticket Number: CTW-1462
Ran into issues long-polling FQS for Basic resources as a Care Team User due to lack of permissions reading those resources. This PR removes that long-poll as well as any query invalidation when reading/dismissing resources. Functionally this just means that when you dismiss a resource it doesn't immediately disappear from the list (it just greys out) and when you're done reading all the resources the red dot doesn't go away until you refresh the page. These feel like reasonable compromises to get this fix out and are actually a pretty big performance improvement to the speed to reading/dismissing resources (since long-polling and invalidating the resource query on every read/dismiss seemed like overkill anyway). 
Tested locally.
Will verify UI after deploy. …

CTW-1462 Removing FQS long poll and query invalidation for read/dismiss

---

.changeset/chilled-suns-shout.md
src/App.tsx
src/components/content/patients/patients-search.tsx
src/components/core/form/combobox-field.tsx

Jira Ticket Number: [CTW-1620](https://zeushealth.atlassian.net/browse/CTW-1620)
This PR fixes a bug in patient search when there are multiple patients with the same name. Previously the `ComboBoxOption`'s value was the label, which comprised the patient's full name. When an option was selected, the `ComboBoxField` would use the label to look up the first occurrence in the results, so if there are 2 or more patients with the same full name, it would always return the first patient.
Now the `ComboBoxOption`'s value is the entire option so we can just return the option's value to the `onCustomSelectChange` callback.
Manually tested in the demo app.
Manually tested with relative dependancies in standalone.
Manually test in all environments
[CTW-1620]: …

[Bug] Fix Patient Search when patients have the same name
